### ISSUE TITLE
Faulty core fixes: Second embedded PHP block closing tag not indented

### ISSUE THREAD

**Issue by pento** [WordPress/WordPress-Coding-Standards#1118]
Given the following test case:

```php
<div>
	<?php a(); ?>
	<?php b( array( 'c' => 'd', 'e' => 'f' ) ); ?>
</div>
```

The `?>` on the second embedded block will not be indented:

```php
<div>
	<?php a(); ?>
	<?php
	b(
		array(
			'c' => 'd',
			'e' => 'f',
		)
	);
?>
</div>
```

A Core example can be seen in `src/wp-content/themes/twentyeleven/404.php`.

**Comment by jrfnl** [comment]
FYI: I know some fixes to the upstream sniff have been made regarding this recently, so it may well be worth it to re-run the fixer and see if the results have improved once PHPCS 3.4.1 comes out.

**Comment by jrfnl** [comment]
We have just verified and the upstream fixes clearly sorted this out and it is now fixed correctly. Closing.
