### ISSUE TITLE
False positive with escaping of object->method for ternary condition

### ISSUE THREAD

**Issue by GaryJones** [WordPress/WordPress-Coding-Standards#1219]
With the following code:
```php
array_walk(
	$upcoming_webinars,
	function ( $webinar ) {
		?>
		<tr>
			<td>
			<?php
			echo ( $webinar->is_too_late_to_register ? '<a href="' . esc_url( $webinar->url ) . '">' : '' );
			// ...rest of function...
	}
);
```

I'm getting the following:

```
 32 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$webinar'. (WordPress.XSS.EscapeOutput.OutputNotEscaped)
```

Line 32 is the line with the `echo`.

There seem to be two issues, probably related, here:

 - `$webinar` is an object that has a method being called - it's not the thing even attempted to be echo'd (the message is misleading).
- The `$webinar->is_too_late_to_register` is also not trying to be echo'd as it's a boolean for the ternary condition.

Removing the outer parentheses on that line doesn't help. In actual fact, removing them on a line just below:

```php
echo ( $webinar->is_too_late_to_register ? '</a>' : '' );
```

actually makes that line get reported with the same error, where otherwise it's doesn't.

**Comment by jrfnl** [comment]
Came across the same thing the other day. The `EscapeOutput` sniff clearly doesn't handle ternaries well (or rather at all).

Until the sniff is fixed, there are two solutions:
```php
// Making it a full fledged `if`:
if ( $webinar->is_too_late_to_register ) {
    echo '<a href="' . esc_url( $webinar->url ) . '">';
}

// Moving the `echo` into the `else` - not pretty, but I suspect it'll work:
( $webinar->is_too_late_to_register ? echo '<a href="' . esc_url( $webinar->url ) . '">' : null );
```

**Comment by JDGrimes** [comment]
I think that it is (or was at one time) supposed to handle ternaries, but there were some quirks. It is difficult to completely handle ternaries without also letting false positives slip through, which is why I never worked all of the quirks out. But if we can find a way to safely handle them, I'm happy to revisit it.

**Comment by jrfnl** [comment]
Marking this as a duplicate of #677.

I'm not closing the issue at this time as it contains useful code samples for the unit tests and discussion complimentary to what's been said in #677.
