### ISSUE TITLE
Clarify the need for using rawurlencode() instead of urlencode()

### ISSUE THREAD

**Issue by johnbillion** [WordPress/WordPress-Coding-Standards#1234]
When usage of `urlencode()` is detected, the warning from `WordPress.PHP.DiscouragedPHPFunctions.urlencode_urlencode` states:

> urlencode() should only be used when dealing with legacy applications rawurlencode() should now be used instead. See http://php.net/manual/en/function.rawurlencode.php and http://www.faqs.org/rfcs/rfc3986.html

This doesn't explain what a legacy application is, or why `rawurlencode()` should be used. The two links provided don't provide any useful information either.

What can we do to improve this message? What's the actual reason for recommending `rawurlencode()` over `urlencode()`?

**Comment by jrfnl** [comment]
I've wondered the same myself quite often and haven't got an answer for you.

It has always been my understanding (after much research I did quite a long time ago) that `rawurlencode()` should be used on _individual_ parts of a URL, i.e. user, password, individual path fragments etc, and that `urlencode()` should be used on query strings and fragments (#).

**Comment by JDGrimes** [comment]
I think this [SO answer explaining the differences between them](https://stackoverflow.com/a/996161/1924128) forms a portion of the rationale for this. `urlencode()` converts spaces to `+` instead of `%20`, which is the way some legacy systems did it but is no longer standard.

**Comment by johnbillion** [comment]
More info about usage: https://www.gyrocode.com/articles/php-urlencode-vs-rawurlencode/

**Comment by GaryJones** [comment]
At least for modern PHP, it seems that `urldecode()` [can handle both](https://3v4l.org/SgHjP), so there doesn't seem to be an obvious reason to use `urlencode()`, when `rawlurlencode()` follows an RFC (unless the generated URL is going to be sent to a system that has a different version of PHP, or has a method of decoding querystrings that doesn't support `%20` for spaces).

As such, the WPCS current message would seem accurate, even if the links are not ideal (perhaps have a wiki page on this repo to outline the perceived issue, and include a link to that instead?).

FWIW, the [WordPress VIP docs](https://wpvip.com/documentation/encode-values-passed-to-add_query_arg/) (and [here](https://wpvip.com/documentation/vip-go/validating-sanitizing-and-escaping/#escaping-securing-output) and [here](https://wpvip.com/documentation/vip-go/code-review-blockers-warnings-notices/#encoding-values-used-when-creating-a-url-or-passed-to-add_query_arg) suggest to use `rawurlencode()` all the time, even for querystrings.

**Comment by jrfnl** [comment]
Based on the above discussion, there is nothing to do here, so closing.
