### ISSUE TITLE
Rename EscapeOutput sniff to LateEscapeOutput ?

### ISSUE THREAD

**Issue by JDGrimes** [WordPress/WordPress-Coding-Standards#1254]
It has been pointed out that the `EscapeOutput` sniff flags all output, whereas some people would like to just catch low-hanging fruit. (See for example #744.) Basically, this sniff is intended to enforce the practice of late-escaping, and some people don't want to follow that (or it is very difficult because of code design). Therefore, it is possible that another output escaping related sniff will be introduced at some point. As such, it has been suggested somewhere (by @grappler, I think) that this sniff be renamed. Since we are going to be renaming things in the next release (and this sniff's name will already be changing from `XSS` to `Security`), I thought this might be a good time to consider whether we want to rename this to something like `LateEscapeOutput`.

The potential downside to this is that we might end up just adding options to this sniff to accommodate folks who just want low-hanging fruit, rather than introducing separate sniff(s). In that case, the name would be problematic if changed, and would be better left as it is.

I'm not really a big fan of encouraging anything other than late escaping, and so I am fine with the sniff name as it is. I just thought it was worth bringing up at this time.

**Comment by GaryJones** [comment]
I'm fine with the name changing, even if no alternative sniff ever materialises.

**Comment by jrfnl** [comment]
I'm ambivalent.

If the sniff is to be renamed, I'd like to suggest the name to be changed to `EscapeOutputLate` instead.
That would allow for a secondary sniff to be called `EscapeOutputEarly` or something.

It's just a small semantic thing, but the sniff is primarily about escaping output. Late/Early are only the timing.

If the sniff would be called `LateEscapeOutput`, it comes across as if the timing is the most important thing, not the escaping.

**Comment by jrfnl** [comment]
@dingo-d and me discussed this. Any sniff for "early escaping" would be neigh impossible to write as there is no context that data will be used in output, so nothing to "listen" for.

If no second sniff will be written, what's the point of renaming the sniff ? (and creating an unnecessary BC-break).

Suggest: close.
