### ISSUE TITLE
Allow a function to specify that it should be subject to certain sniffs

### ISSUE THREAD

**Issue by johnbillion** [WordPress/WordPress-Coding-Standards#1257]
Given the following code, a sniff error will be raised for the lack of escaping at the last line where `get_my_html()` gets echoed out. This can be fixed with an appropriate inline comment, but the fundamental problem with this code is that `get_my_html()` does not escape the attribute value that's passed in.

I'd like to be able to add a comment to this function which opts it in to the `WordPress.XSS.EscapeOutput.OutputNotEscaped` sniff, which normally only operates on output. I'd like it to operate on the return value of the function.

```php
function get_my_html( $value ) {
	return sprintf(
		'<element attribute="%s">Hello</element>',
		$value
	);
}

echo get_my_html( '"><script>alert(xss)</script><"' );
```

Is something like this remotely possible? Is it a bit of a stretch?

**Comment by JDGrimes** [comment]
I think this is possible. Might be as simple as temporarily adding `return` to the list of printing functions while sniffing the function's body.

**Comment by jrfnl** [comment]
> Might be as simple as temporarily adding return to the list of printing functions while sniffing the function's body.

Just FYI: That won't work, as `return` has its own token `T_RETURN` and the sniff looks for `T_STRING` function calls.

**Comment by jrfnl** [comment]
@johnbillion Have you tried passing the function to WPCS as a `customPrintingFunctions` ? Or maybe add a separate method `print_my_html()` which just does an `echo get_my_html()` and add that to the `customPrintingFunctions` to be precise.

See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#xss-custom-printing-functions for more information about this.

**Comment by jrfnl** [comment]
@johnbillion Any feedback ?

**Comment by jrfnl** [comment]
Closing for lack of reply.
