### ISSUE TITLE
Adjust sniffs to allow for the new PHPCS whitelist comment tokens

### ISSUE THREAD

**Issue by jrfnl** [WordPress/WordPress-Coding-Standards#1272]
The new PHPCS native whitelist tokens as introduced in PHPCS 3.2.0, each have their own PHPCS native token.

These tokens are currently not (yet) taken into account within WPCS sniffs and will cause false positives and incorrect fixes until they are.

Until the WPCS minimum PHPCS requirement has gone up beyond PHPCS 3.2.0, some sort of compatibility layer is needed to account for these.

**Comment by jrfnl** [comment]
Been working on this, however am finding some upstream bugs/inconsistencies with the new tokens.
I've opened an issue upstream about these: https://github.com/squizlabs/PHP_CodeSniffer/issues/1826

**Comment by mundschenk-at** [comment]
Any idea when this will land? Upstream seems to be "waiting for feedback".

**Comment by jrfnl** [comment]
@mundschenk-at Upstream the changes landed and were published in `v3.2.+`, so the fact that the next release is probably coming out soon is besides the point (other than that it will make life easier when that version becomes the minimum support PHPCS, but that's not the case yet.

While working on this, I discovered quite some bugs with had to be reported back upstream (and have since been fixed there).
After the last phpcs annotations tokenizer changes (last week), I haven't had the chance to evaluate where we are at.

The short of it is, that I was stuck on phpcs:annnotations being used on a line on their own as the first line of a multi-line array and the fixer in that not correctly being triggered.

Other than that, I recall having fixed the other (7/8) sniffs which were affected by this already. So it's literally just the last bit.

Anyway, as I'm ill, I guess for me to get better would help (on SO many levels), when I do, this *is* on my too do list.

**Comment by mundschenk-at** [comment]
@jrfnl I meant the upstream issue https://github.com/squizlabs/PHP_CodeSniffer/issues/1826, which I thought was a blocker for your WIP being merged. If there's a way to help out, I'm willing to try (though getting my head into PHPCS internals is something that would probably take some time).

Anyway, I hope you get well soon!

**Comment by jrfnl** [comment]
Except for the `ArrayIndentation` sniff, all known issues with regards to this issue have been fixed and will be included in the `1.0.0` release.

**Comment by jrfnl** [comment]
I'm going to close this issue now. The `ArrayIndentation` sniff will likely be replaced at some point in the future by a PHPCSExtra sniff. We should make sure that that sniff handles this correctly.
