### ISSUE TITLE
Advice on writing unit tests for irregular whitespace characters

### ISSUE THREAD

**Issue by dingo-d** [WordPress/WordPress-Coding-Standards#1382]
## Problem

I wanted to create a sniff that will check the irregular whitespace characters like the one in the [ESLint](https://eslint.org/docs/rules/no-irregular-whitespace) rule.

I wanted to create unit test for it before trying to work on the actual sniff, but I'm not exactly sure how to test it, because even if I drag the characters from the character viewer (on mac), I get things like

><0x0b>

Written in the file, and the only irregular whitespace I can produce on the mac is by typing option+space (without actually it being typed out like above). 

So I'd like some advice about how to approach it, and if we want a sniff that checks for irregular white space.

## Motivation

The motivation behind the sniff was that I got errors in my php code, and I couldn't see where the errors were coming from, unless I highlighted the code in the editor (Sublime), where I could see that there is not a dot in my space.

So this sniff would detect these irregular white spaces in the code and warn the user not to use them.

## To do

* Discuss if we want/need such a sniff
* Create `IrregularWhitespaceSniff` that will check these irregular white spaces
* Test

**Comment by jrfnl** [comment]
Without voicing an opinion about whether or not this should be checked by WPCS, I have a couple of general remarks related to this idea:

1. For irregular whitespace at the start and end of a file which could lead to the dreaded "headers already send" issue: this will be covered by the `Squiz.Whitespace.SuperfluousWhiteSpace` sniff once PHPCS 3.3.1 comes out.
See: https://github.com/squizlabs/PHP_CodeSniffer/pull/2040
2. I'm not sure a sniff will be the best/easiest way to find these. You would need to examine quite a few token types (all text tokens and some of the less common tokens associated with tokenizer issues).
Running a regex for this over each file in a plugin/theme might be more performant, especially as finding these type of whitespaces is reasonably rare anyway.
3. If a sniff would be decided to be the way to go - I managed to create some test data for the PR mentioned above, by copying and pasting from MS Word to Notepad while making sure the test file encoding was set to UTF-8.
If worse comes to worse, you could even create some test files by letting PHP write the characters you want to test for to a file.

**Comment by dingo-d** [comment]
Thanks for the input. I'll start to work on this just in case it gets picked up :)

**Comment by dingo-d** [comment]
This hasn't picked up any traction, so we can close it. I'll open a placeholder issue in the PHPCSExtra for this.
