### ISSUE TITLE
Warn for using wp_enqueue_*() with args other than handle

### ISSUE THREAD

**Issue by GaryJones** [WordPress/WordPress-Coding-Standards#1439]
Untangled from #1146, which just focused on ensuring version and in_footer params were added.

In https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1146#issuecomment-329915299 @westonruter said:
> Note that technically these sniffs should be about `wp_register_script()` and `wp_register_style()`. The fact that the corresponding enqueue functions allow you to enqueue and register at the same time is just a shortcut, and one that I don't think is a good practice. I think it's better to register all your scripts during `wp_default_scripts` and `wp_default_styles`, at least for core feature plugins, and then later to just `wp_enqueue_script( $handle )`. This ensures you can just reference a handle regardless of the context where you're enqueueing the asset, and there isn't a need to copy the $src in multiple places.
>
> If possible, it would also be nice to include `wp_scripts()->add()` and `wp_styles()->add()` in these checks, also assuming that variables `$wp_scripts` and `$scripts` or `$wp_styles` and `$styles` may be used instead. Examples: WordPress/better-code-editing:wp-includes/script-loader-addendum.php@0.7.0

Then @westonruter [followed-up](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1146#issuecomment-408643564) with:

> In regards to [the comment above], I just noticed that in #1378 there is no warnings raised for calling `wp_enqueue_script()` and `wp_enqueue_style()` with args other than the handle. In other words, it's not mandating that you register scripts/styles prior to enqueueing. In working on PWA (https://github.com/xwp/pwa-wp/issues/25) I realized there is another key benefit to registering your scripts and styles unconditionally and then conditionally enqueueing: it allows for a service worker to include all of a site's registered scripts and styles to include in the precache manifest. Otherwise, the service worker can only do runtime caching of scripts/styles it finds while a user navigates a site.
>
> I'd be happy to open a PR to propose this new sniff warning for `EnqueuedResourceParameters`.

@jrfnl [queried this](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1146#issuecomment-408644889) with:
> Personally I'm not sure whether WPCS should warn about a shortcut which was build into WP to specifically act as a shortcut. I'm not familiar with caching by service workers, so I'm not sure whether this is an edge case or common practice. Altogether, I'd like to hear some more opinions from people before we decide whether or not to add this to WPCS.

**Comment by westonruter** [comment]
So at least for core this sniff would be needed since scripts are registered prior to enqueueing. It was not be required for themes, but it could still be a good practice.

**Comment by jrfnl** [comment]
Just for the record: this sniff is not used by Core and not included in the `WordPress-Core` ruleset nor the Core `phpcs.xml.dist` file.

**Comment by jrfnl** [comment]
This ticket hasn't really gained any traction over the past few years, so I would like to suggest closing it.
