### ISSUE TITLE
Specifying custom SQL escaping functions (similar to output escaping functions)

### ISSUE THREAD

**Issue by Flimm** [WordPress/WordPress-Coding-Standards#1460]
Let's take this code:

```php
<?php
$sql = $wpdb->prepare( "SELECT * FROM `" . esc_sql_name( $table ) . "`;" );
```

Running `phpcs` on this file will give these errors:

```
--------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------
 2 | ERROR | Use placeholders and $wpdb->prepare(); found esc_sql_name
   |       | (WordPress.DB.PreparedSQL.NotPrepared)
 2 | ERROR | Use placeholders and $wpdb->prepare(); found $table (WordPress.DB.PreparedSQL.NotPrepared)
--------------------------------------------------------------------------------------------------------------
```

`esc_sql_name` is a function I wrote, and I would like to tell PHPCS that I trust this function to return SQL that is considered "safe", the same way it would trust `esc_sql`.

This is similar to an existing feature for `WordPress.Security.EscapeOutput` . In PHPCS configuration, you can define `customEscapingFunctions` and add any custom functions that escape strings to be ready for output.

I'm using PHPCS 3.3.1, WPCS 1.0.0 and PHP version 7.1.16.

This feature would be useful to me. Right now, there isn't a built-in function or a function shipped with WordPress that escapes identifiers to be used in SQL. You can't use `esc_sql` or `%s` in a prepared statement, because these are meant for escaping string literals, and not identifiers. Sometimes, the table or column name is generated dynamically, in which case a custom function like the one I wrote `esc_sql_name` is useful. It would be useful if I could get PHPCS to recognise this function.

**Comment by jrfnl** [comment]
Marking this as a feature request.

For now, you can get "error" by actually using the `prepare()`, as in:
```php
$sql = $wpdb->prepare(
    "SELECT * FROM `%1$s`;",
    esc_sql_name( $table )
);
```

Note: using the numbered variant of the placeholder means that `$wpdb->prepare()` will not quote the string for your query, which is what you want here.

Does that help ?

**Comment by Flimm** [comment]
Thanks for the reply. I assume you meant to use single quotes in your example, like this:

```php
$sql = $wpdb->prepare(
    'SELECT * FROM `%1$s`;',
    esc_sql_name( $table )
);
```

I did not know that numbered placeholders will not generate quoted values in the prepare statement, that's useful. However, it will still escape the string in the way that is appropriate for string literals, which is not what I want here. MySQL's identifiers need to be escaped in a different way (basically, a single backtick `` ` `` needs to be converted to a double backtick ``` `` ```), so this additional escaping might get in the way of that. Thank you for your time, @jrfnl .

**Comment by jrfnl** [comment]
> I assume you meant to use single quotes in your example

Yes, of course, that was just not relevant to the point I was making :smile_cat:

> However, it will still escape the string in the way that is appropriate for string literals, which is not what I want here. MySQL's identifiers need to be escaped in a different way (basically, a single backtick ` needs to be converted to a double backtick ``), so this additional escaping might get in the way of that.

I see what you mean and understand the issue. I would suggest opening a Trac ticket with a feature request to add such a method - i.e. MySQL identifier escaping - to WP Core.

All the same, I think using back-ticks *within* MySQL identifiers is bad practice, so shouldn't be done in the first place, but, that's just my opinion.

**Comment by jrfnl** [comment]
I'd like to suggest closing this issue in favour of encouraging people to start using `%i` for table names once it is available (likely to be in WP 6.2).

Refs:
* https://core.trac.wordpress.org/ticket/52506
* https://github.com/WordPress/WordPress-Coding-Standards/pull/2072

**Comment by Flimm** [comment]
That's fantastic news that WordPress 6.2 will hopefully include support for `%i` for table names!

I suppose there may be some people out there who would need the requested functionality to scan code meant for older versions of WordPress, but I'm OK with closing this issue once WordPress 6.2 ships with `%i` support. I don't want to close this issue before then, in case it doesn't.

**Comment by Flimm** [comment]
Wonderful! I'm delighted at this news.
