### ISSUE TITLE
WPCS 3.0: Remove the deprecated Sniff::has_whitelist_comment() method

### ISSUE THREAD

**Issue by jrfnl** [WordPress/WordPress-Coding-Standards#1583]
PR #1580 for WPCS 2.0.0 deprecated the WPCS native whitelist comments and the associated `Sniff::has_whitelist_comment()` method.

In WPCS 3.0.0 this method and all calls to it should be removed.

>  Note: all unit tests testing that the WPCS native whitelist comments are being respected should also be removed at that time. Or alternatively, they can remain and it should be verified that the WPCS native whitelist comment make no difference anymore.

**Comment by kkmuffme** [comment]
Is there any possibility of this getting released? Since the `has_whitelist_comment` function is quite slow

**Comment by jrfnl** [comment]
@kkmuffme It will be released as part of WPCS 3.0.0.

**Comment by kkmuffme** [comment]
It's been multiple years since this PR was merged, which is why I asked :-)

**Comment by jrfnl** [comment]
I am fully aware.
