### ISSUE TITLE
Check for post type key length in register_post_type

### ISSUE THREAD

**Issue by ipetty14** [WordPress/WordPress-Coding-Standards#1696]
## Is your feature request related to a problem?
I noticed that while registering a custom post type, my post type key was more than 20 characters and therefore failing to show up on the admin panel. I had to check the developer handbook to see that the post type key must be 20 characters or less

## Describe the solution you'd like
Adding a check for a max of 20 characters would be great.

For example: 
`register_post_type( 'post_type', $args );`
would succed without error.

However, 
`register_post_type( 'post_type_key_is_too_long', $args );`
would throw an error and a suggestion for the user to shorten the title to meet the WordPress Standards

See the link below for the reference to the specific character length. 
[Register Post Type](https://developer.wordpress.org/reference/functions/register_post_type/)

**Comment by jrfnl** [comment]
@ipetty14 Thanks for the suggestion. I like the idea, but am afraid that a sniff would only rarely catch this as it is pretty common to call the function like so: `register_post_type( $post_type_name, $args );` and there is no reliable way for PHPCS to determine the run-time value of `$post_type_name`.

So, yes, I do think adding a sniff for this would be a good idea, but I also think it's low priority.

**Comment by jrfnl** [comment]
Loosely related to #871
