### ISSUE TITLE
Auto formatting and Quick Fix

### ISSUE THREAD

**Issue by TNHSAesop** [WordPress/WordPress-Coding-Standards#1710]
I've installed this extension and it's giving me a zillion errors mostly related to formatting. Are there recommended and supplementary extensions for the WordPress coding standard to take advantage of the alt + shift + f auto format feature in VS Code? Right now the auto format auto formats with spaces for example but phpcs WordPress standard requires tabs for instance. There also seems to be lots of issue detection in code but the quick fix options aren't available. 

I'm wondering if there are supplemental extensions to fix these problems or if these are just feature gaps?

**Comment by jrfnl** [comment]
> Are there recommended and supplementary extensions for the WordPress coding standard to take advantage of the alt + shift + f auto format feature in VS Code?

Have a look at the [WPCS wiki](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki) to see about configuring WPCS to work with your IDE.

> I've installed this extension and it's giving me a zillion errors mostly related to formatting
> There also seems to be lots of issue detection in code but the quick fix options aren't available.

Have a look at the [WPCS Readme](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/#rulesets) regarding the various standards available.
For instance: the `WordPress-Core` ruleset will report on things which are mostly auto-fixable, while if you choose to use the stricter, but more extensive `WordPress` ruleset which also includes `Extra` and `Docs`, you will see a lot more things which can't be auto-fixed.

> I'm wondering if there are supplemental extensions to fix these problems or if these are just feature gaps?

Things which can't be auto-fixed are rarely feature gaps. Those are things which need the attention of a human to determine the best course of action.
Things like security issues or missing documentation are not things which will ever be auto-fixable.

**Comment by jrfnl** [comment]
@TNHSAesop Just checking: did my previous reply help ?

**Comment by jrfnl** [comment]
Closing for lack of response.
