### ISSUE TITLE
Add WP_IMPORTING to whitelisted core constants

### ISSUE THREAD

**Issue by ocean90** [WordPress/WordPress-Coding-Standards#1719]
## Is your feature request related to a problem?
`WP_IMPORTING` is not defined in `wp-includes/default-constants.php` but can be used to tell WordPress that an import is happening. It's recommended to set the constant when migrating a lot of data.

## Describe the solution you'd like
I think `WP_IMPORTING` should be part of `PrefixAllGlobalsSniff::$whitelisted_core_constants`.

## Additional context
Usage of `WP_IMPORTING`: https://github.com/WordPress/WordPress/search?q=WP_IMPORTING

**Comment by jrfnl** [comment]
@ocean90 The question is: should `WP_IMPORTING` ever be defined from within plugins or themes ?

The `PrefixAllGlobals` sniff is not intended for use with WP Core, at least, not at this time.

**Comment by ocean90** [comment]
The answer to that question is the reason why I created the issue. Use case: A migration script within a plugin through a WP-CLI command.

**Comment by jrfnl** [comment]
@ocean90 For an isolated usecase like that, you can use a whitelist comment.

I don't think we should encourage plugins/themes defining that constant and adding it to the list in the `PrefixAllGlobals` sniff could be interpreted as implicit "approval".

**Comment by dingo-d** [comment]
Yeah, themes even explicitly forbid import data, and adding importing functionality is clear plugin territory.
