### ISSUE TITLE
Moving to WordPress organisation broke travis & readme

### ISSUE THREAD

**Issue by NielsdeBlaauw** [WordPress/WordPress-Coding-Standards#1747]
## Bug Description
Feedback from travis is not correctly processed in the repository for new pull-requests. The README is missing several badges and is still pointing to the old repository in a lot of cases.

**Comment by dingo-d** [comment]
The packagist is still under https://packagist.org/packages/wp-coding-standards/, should this be moved to `wordpress` org?
