### ISSUE TITLE
Identify non-numeric values being used with arithmetic operations / PHP 7.1+

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#1790]
## Is your feature request related to a problem?
Since PHP7.1, php throws a notice when non-numeric values are being used with arithmetic operators.

e.g.

```
$non_existing_option = get_post_meta( ... );
$result = $non_existing_option + 10;
```

This means when upgrading your PHP to 7.1+ and using WP with various plugins/themes (from woocommerce.com or the WP plugin directory) you will get loads of notices.

## Describe the solution you'd like
It would be incredibly nice if there was a check for basic assignments, this means literals ($a=...) and WP functions (get_post_meta,...), just like in the example above.

In a next step perhaps even for custom functions, if they have their phpdoc with the return type specified.

This would allow us to fix code beforehand as well as make sure no new code is introduced that will create these notices (to some extent at least)

**Comment by jrfnl** [comment]
@kkmuffme Thanks for the idea, but unfortunately a sniff like that will not be created.

1. This is not something which can be sniffed reliably with a static analysis tool like PHPCS.
    The simple example you gave reflects maybe 2% of code affected, the other 98% of code affected by this issue is code where it will be impossible to determine for PHPCS what the type held by the variable will be.
    Think: what if there was an `apply_filters()` between the two lines of your example ?
2. If at all, this would not be a sniff which would be added to WPCS, but a sniff for the [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility) standard which I'd strongly suggest you add to your ruleset.
    For PHPCompatibility I have looked into this before and came to the conclusion in [1].

**Comment by kkmuffme** [comment]
Thanks a lot for the feedback
