### ISSUE TITLE
Discourage use `current_time( 'timestamp' )`

### ISSUE THREAD

**Issue by Rarst** [WordPress/WordPress-Coding-Standards#1791]
## Is your feature request related to a problem?

`current_time()` with `timestamp` or `U` format produces a "WordPress timestamp", a sum of Unix timestamp and current time zone offset.

While historically entrenched in core, the use of such timestamps is deeply problematic and we are working on eliminating them in favor of real Unix timestamps and full interoperability with PHP.

## Describe the solution you'd like

- `current_time( 'timestamp', true )` / `current_time( 'U', true )`  are equivalent to `time()` and should be _replaced_ with it
- `current_time( 'timestamp' )` / `current_time( 'U' )` should be _discouraged_ in favor of requesting non-timestamp format, or otherwise refactoring the usage

## Additional context (optional)

The use of `current_time( 'timestamp' )` had been mostly eliminated from core in [#40657](https://core.trac.wordpress.org/ticket/40657). Minimal usage in unit tests and older functions that _must_ operate with WP timestamps for backwards compatibility reasons remains.

**Comment by GaryJones** [comment]
Just because I missed the emphasis here on first read - the bad thing here isn't the use of `current_time()`, but more the use of the first arg being `timestamp`.

**Comment by Rarst** [comment]
Yes, `current_time()` works fine for other formats (now, after round of fixes).

**Comment by jrfnl** [comment]
I'm working on adding this check. I'm inclined to add it to the `TimezoneChange` sniff as all date/time related function checks are then contained in one sniff, though this one needs quite some additional logic.
Alternatively I could add a stand-alone sniff, `WP.CurrentTimeTimeStamp` maybe ?

Opinions ?

**Comment by Rarst** [comment]
I think (hope) we head towards formally deprecating WP timestamps in the future, so it might make more sense to combine issues related to them as separate sniff. Would make it more convenient down the road to handle them as a separate unit of mess.

PS "timestamp" is a single word traditionally in computing context, so `CurrentTimeTimestamp` for name then :)

**Comment by jrfnl** [comment]
@Rarst I just noticed this comment in the Dev docs: https://developer.wordpress.org/reference/functions/current_time/#comment-2373

We may need to find someone with edit rights to Dev docs to remove the comment, or at the very least another comment should be left discrediting the comment.

**Comment by Rarst** [comment]
Thanks for letting me know, I would probably need to leave bunch of comments around. Will do when new functions are scanned into reference so I can refer to them.
