### ISSUE TITLE
Require alternative syntax for control structures in templates

### ISSUE THREAD

**Issue by westonruter** [WordPress/WordPress-Coding-Standards#18]
It is easy to sneak in logic into templates. I think a handy way to remind yourself not to do this is to always use PHP's alternative syntax for control structures in WP templates: http://www.php.net/manual/en/control-structures.alternative-syntax.php

The use of this syntax lends itself much better to meshing with markup since the tags are much more apparent, and it makes it much easier to indent with markup. Lastly, it is much more readable to see `<?php endif; ?>` then just `<?php } ?>`

**Comment by dingo-d** [comment]
This is an opinionated proposal that shouldn't belong in WPCS.

There is already an external sniff in the [PHPCSExtra](https://github.com/PHPCSStandards/PHPCSExtra/blob/develop/Universal/Sniffs/ControlStructures/DisallowAlternativeSyntaxSniff.php) ruleset which can be used for this purpose.
