### ISSUE TITLE
WPCS 3.0.0: Remove deprecated WP.TimezoneChange sniff

### ISSUE THREAD

**Issue by jrfnl** [WordPress/WordPress-Coding-Standards#1819]
As per the proposal in #1805, the `WordPress.WP.TimezoneChange` sniff has been deprecated in PR #1807 / WPCS 2.2.0.

In the next major release of WPCS (3.0.0), this sniff should be removed.

**Comment by paulschreiber** [comment]
Seeing this now. It's creating a lot of noise.

**Comment by jrfnl** [comment]
@paulschreiber Unless the sniff is explicitly included in a custom ruleset, you shouldn't see any noise coming from this....

**Comment by paulschreiber** [comment]
I'm seeing it via the `PHPCompatibilityWP` ruleset.

**Comment by jrfnl** [comment]
@paulschreiber That's not possible as the [`PHPCompatibilityWP`](https://github.com/PHPCompatibility/PHPCompatibilityWP) ruleset is completely unrelated to WPCS and does not include any WPCS sniffs.

**Comment by paulschreiber** [comment]
Turns out to be a problem with VIP Go's ruleset.

**Comment by paulschreiber** [comment]
(Please close this.)
