### ISSUE TITLE
Bug: "Using the WPCS native whitelist comments is deprecated" for normal comment

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#1835]
## Bug Description

I get this error:
Using the WPCS native whitelist comments is deprecated. Please use the PHPCS native "phpcs:ignore Standard.Category.SniffName.ErrorCode" annotations instead. Found: // incorrectly spelled word;priority;spelling suggestion;n

for:

```
// incorrectly spelled word;priority;spelling suggestion;
$spellchecked_words = $word_groups[1] . ';' . $word_group[0] . ';' . $word_group[1] . ';' . PHP_EOL;
```

I am not using any WPCS comment or anything, no idea why I get this error at all here.

**Comment by GaryJones** [comment]
Good catch! I can reproduce.

More minimal case:

```php
// spelling.
$foo = '';
```

If the word `spelling` is removed (or any letter of it), then the violation disappears.

**Comment by jrfnl** [comment]
The old-style WPCS native whitelist comments will be removed in WPCS 3.0, which means that that message will then no longer be thrown either.

As WPCS 3.0 is planned for somewhere over the next few months, I suggest to just ignore the message from within your custom ruleset for now.

```xml
<?xml version="1.0"?>
<ruleset name="My Plugin standard">
    <rule ref="WordPress">
        <exclude name="WordPress.WP.CapitalPDangit.DeprecatedWhitelistCommentFound"/>
    </rule>
</ruleset>
```

Also see #1583

**Comment by kkmuffme** [comment]
Thanks
