### ISSUE TITLE
Let sanitize_hex_color() count as an escape function

### ISSUE THREAD

**Issue by GaryJones** [WordPress/WordPress-Coding-Standards#1846]
Related: Comments in #780 

## Bug Description
When PHP outputs some CSS, you might see:

```php
color: <?php echo sanitize_hex_color($text_color); ?>
```

However, that gives a violation of:

> Error: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'sanitize_hex_color' (WordPress.Security.EscapeOutput.OutputNotEscaped).

The [`sanitize_hex_color()` function](https://github.com/WordPress/WordPress/blob/f545bb3f634c8e949db9051bd88924df592c3337/wp-includes/formatting.php#L5905) returns either a valid 3 or 6-character hexadecimal colour code, or an empty string. In typical usage (putting the value into a CSS output) there is nothing to escape.

As such, I propose that `sanitize_hex_color()` is considered to already be escaped, and the violation is not shown. The alternative would be something like `esc_attr()`, which has a less strict allowance of values.

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | 7.3
| PHP_CodeSniffer version | 3.5
| WPCS version            | 2.2.0
| WPCS install type       | Composer

## Additional Context (optional)
We might also consider `sanitize_hex_color_no_hash()` and possibly `maybe_hash_hex_color()` as well, since they are ultimately wrappers for `sanitize_hex_color()` as well.

## Tested Against `develop` branch?
- [x] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by jrfnl** [comment]
Reviewed the code in the functions and makes sense to me (for all three functions). :+1: 

I'm a little surprised they aren't in the list already, though they are in the `$sanitizingFunctions` list.

**Comment by paulschreiber** [comment]
@GaryJones Can you approve/merge the PR?
