### ISSUE TITLE
Check for unnecessary esc

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#1851]
## Is your feature request related to a problem?
When code is refactored, where things which were directly output before are now assigned to variables, the esc_html/attr often stay as they were even though they are not necessary anymore.

## Describe the solution you'd like
Inform the user if he used an esc_ function where it's not necessary because the variable isn't output.

## Additional context (optional)
The benefit is purely cosmetical. The advantage in performance is negligent.

**Comment by jrfnl** [comment]
Some thoughts on this:
* Often using `esc_attr()`/`esc_html()` early - like when preparing an HTML snippet which will be used in output a little later - simplifies code and prevents needing to use the more expensive `wp_kses()` functions.
* As WPCS will not necessarily know if that is what's being done, sniffing for this will be extremely prone to false positives/negatives.

**Comment by kkmuffme** [comment]
@jrfnl you are right.

How about a more restricted approach:
when using it in an array for e.g. `'desc' => `,... (inclding name, type, id,...) it should report unnecessary escaping?

**Comment by jrfnl** [comment]
Same thing. That array may be used in a `sprintf()` with another HTML wrapper and when the array contains a mix of hard-coded values and values which need escaping, using the escaping in the array may be more efficient.
