### ISSUE TITLE
trigger_error is counted as an output function for escaping purposes

### ISSUE THREAD

**Issue by rmccue** [WordPress/WordPress-Coding-Standards#1864]
## Bug Description

`trigger_error` is treated as a HTML output method, and hence requires escaping.

Errors are only output as part of the HTML when `show_errors` is set to true, which is not common in production environments. Error text is not necessarily HTML data, and doesn't require escaping.

## Minimal Code Snippet

```php
trigger_error( 'Undefined config option: ' . $key );
```

## Error Code

`WordPress.Security.EscapeOutput.OutputNotEscaped`

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | 7.1.32
| PHP_CodeSniffer version | 3.5.4
| WPCS version            | 1.2.1
| WPCS install type       | Composer project local

## Additional Context (optional)

Problem exists in latest WPCS: https://github.com/WordPress/WordPress-Coding-Standards/blob/dd86ccddab77f4631f005893a8b7786b5311efe3/WordPress/Sniff.php#L459

Given this is environment-dependent, I think the rule makes sense by default, but a way to configure or override it would be good. Currently, it's possible to add additional functions, but not remove the built in ones in Sniff.php (AFAIK?)

## Tested Against `develop` branch?
- [x] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by jrfnl** [comment]
> Errors are only output as part of the HTML when show_errors is set to true, which is not common in production environments. Error text is not necessarily HTML data

All of these are actually arguments why it *should* be escaped:
* You don't know the environment in which the code is run, so should take all possibilities into account.
* Arbitrary variables passed to `trigger_error()` may contain HTML and - most of the time - that HTML should be stripped for an error message.

> I think the rule makes sense by default, but a way to configure or override it would be good.

That's what the whitelist comments are for:
```php
// phpcs:ignore WordPress.Security.EscapeOutput -- $key is safe.
trigger_error( 'Undefined config option: ' . $key );
```

Does that help ?

**Comment by rmccue** [comment]
> You don't know the environment in which the code is run, so should take all possibilities into account.

We know for certain the environment the code is being run in, so we know that `trigger_error` and `error_log` are not output functions. (We control the production environment as well as local environments.)

We also use these functions extensively for informative logging in production environments. Escaping the content of these plain-text messages would lead to double-encoding bugs.

(Actually, we also know that all the `_deprecated_...` functions won't cause output as well, FWIW.)

> That's what the whitelist comments are for:

We need to be able to turn the rule on or off for entire codebases. Unlike similar sniffs with subclasses of [AbstractFunctionRestrictionsSniff](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/AbstractFunctionRestrictionsSniff.php), we can't turn this on or off for the entire codebase using a parameter currently. Also, because the function name doesn't form part of the message, we can't override severity to `0` in the config either.

To control this at the config level currently, we would need to subclass `EscapeOutputSniff` and manually override the property (or override one of the methods). The class already has a `customPrintingFunctions` property to allow additional functions to be specified in configuration, so providing the reverse to remove functions would be very useful.

**Comment by jrfnl** [comment]
> The class already has a customPrintingFunctions property to allow additional functions to be specified in configuration, so providing the reverse to remove functions would be very useful.

But not secure in 99% of the cases. If we'd add that option, I expect that in most cases it will be used by people to silence errors which they can't be bothered with or don't know how to fix.

Your use-case is very specific and not the default for a WP environment. Sniffs should be based on the rule, not the exception.

> To control this at the config level currently, we would need to subclass EscapeOutputSniff and manually override the property

Yes, extending the sniff and overloading the `$printingFunctions` property should work and is what I would recommend for your specific usecase.

Or exclude the whole sniff completely. That's also an option of course, but do so at your own risk.

**Comment by rmccue** [comment]
I'd argue that printing errors in HTML is more likely the exception in production environments, but sure.

We've gone with the subclassing option for now. It's [available here](https://github.com/humanmade/coding-standards/blob/b3b46897dfb031a589e55aba5ff0be3a7e6fd18b/HM/Sniffs/Security/EscapeOutputSniff.php) if anyone else needs it.

(It will likely break on newer wpcs versin, as the namespaces have changed.)
