### ISSUE TITLE
Interfaces rules

### ISSUE THREAD

**Issue by mdenisenko** [WordPress/WordPress-Coding-Standards#1868]
I have interface Storage.

1. What should WPCS interfaces be called?

- IStorage
- I_Storage
- InterfaceStorage
- Interface_Storage
- StorageInterface
- Storage_Interface.

2. What should be called file names for interfaces?

- interface-storage

**Comment by dingo-d** [comment]
We don't have an agreement about this atm.

Related: #1327, #1859

**Comment by jrfnl** [comment]
Closing as a duplicate of #1859. Please continue the discussion there.
