### ISSUE TITLE
How to create a custom standard based on the WPCS standard?

### ISSUE THREAD

**Issue by cagross** [WordPress/WordPress-Coding-Standards#1872]
Hello.  I'm already using PHPCS for VSCode, and have it configured to load the WPCS standard from this repo.  It is working, and WPCS rules are flagged in VSCode, as expected, and as desired--thanks for that.

But I would now like to create a custom standard, based on the WPCS standard, and I am having trouble.  Specifically, I have created a custom XML file (`phpcs.xml`), and in it, is a line:

`<rule ref="/path/to/standard">`

What exactly do I enter for `/path/to/standard` here?

On my (Windows) computer, the `wpcs` folder is located in:

`C:\Users\snarl\development-snarl\development-wordpress\vendor\wp-coding-standards\wpcs`

When I specify that path in the `<rule ref="">` line, then open a PHP file in VSCode, it displays this error:

`error:  phpcs: Uncaught Error: Class 'WordPressCS\WordPress\Sniff' not found in C:\Users\snarl\development-snarl\development-wordpress\vendor\wp-coding-standards\wpcs\WordPress\Sniffs\Arrays\ArrayDeclarationSpacingSniff.php:42
`

[Here](https://pastebin.com/WppPe8D4) is a link to my full XML file.

In my case, I installed the XML file into the same folder that houses the VSCode .exe file (C:\Users\snarl\AppData\Local\Programs\Microsoft VS Code).

Thanks.

**Comment by cagross** [comment]
I figured out my problem.  It was two fold:

1.  I had accidentally deleted `ruleset.xml` from `wpcs/WordPress`.  Oops!

2.  I specified this path in the `<rule ref="/path/to/standard">` line:

`C:/Users/snarl/development-snarl/development-wordpress/vendor/wp-coding-standards/wpcs/WordPress`

When I did both, the custom ruleset was indeed loaded and accepted by PHPCS for VSCode, and it was based on the WPCS ruleset.

So we can consider this closed :-)

**Comment by jrfnl** [comment]
@cagross Glad you got it working and thanks for sharing the answer for future searchers.
They may also find this article useful: https://tommcfarlin.com/php-codesniffer-in-visual-studio-code/

> I specified this path in the `<rule ref="/path/to/standard">` line: `C:/Users/snarl/development-snarl/development-wordpress/vendor/wp-coding-standards/wpcs/WordPress`

Pro-tip: If VSCode worked with the named `WordPress` ruleset before changing to your own, you probably don't need to supply the path, but can just use the name (as it should be registered with the PHPCS install used by VSCode), i.e. `<rule ref="WordPress">`.

Also - though I'm not sure if this is a ruleset you want to use for all your projects or just for one particular project, if it is a _project_ ruleset, saving it as `phpcs.xml.dist` in the project root should allow VSCode to pick up on it automatically and allows for other contributers to the project to know what rules you are using for CS.

Hope that helps a little too.

**Comment by cagross** [comment]
> If VSCode worked with the named WordPress ruleset before changing to your own, you probably don't need to supply the path, but can just use the name (as it should be registered with the PHPCS install used by VSCode), i.e. <rule ref="WordPress">.

OK right, good point.  I didn't think to try that.

> Also - though I'm not sure if this is a ruleset you want to use for all your projects or just for one particular project, if it is a project ruleset, saving it as phpcs.xml.dist in the project root should allow VSCode to pick up on it automatically and allows for other contributers to the project to know what rules you are using for CS.

OK got it. I've actually already saved `phpcs.xml` in a different file location, which suits me for now.  But this is good to know for the future, thanks!
