### ISSUE TITLE
List of full names of sniffs

### ISSUE THREAD

**Issue by ghnp5** [WordPress/WordPress-Coding-Standards#1879]
Hello,

Where can I find a list of all sniffs that I can use with this coding standard?

I was looking for a PHPCS sniff that checks for "in_array" strict parameter, and I realized this Standard does it just because Google brought me to this issue: https://github.com/WordPress/WordPress-Coding-Standards/issues/829

However, the only way I could figure out what's the name of that specific sniff was by looking at your change log, and eventually find: **WordPress.PHP.StrictInArray**

I'd like to see a full list (and descriptions) of all the sniffs you have, so I can consider them and manually add each of those I'm interested in, to my "phpcs.xml" file.

Unfortunately, this page doesn't show the names of the sniffs (e.g. "WordPress.PHP.StrictInArray"):
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/

Thank you very much.

**Comment by jrfnl** [comment]
@ghnp5 PHPCS has that functionality build-in. Just run `phpcs --standard=WordPress -e` to _explain_ the standard i.e. list all the sniffs this standards uses, including the WPCS native ones.

Side-note: the `WordPress.PHP.StrictInArray` sniff will most likely be moved to the [`PHPCSExtra`](https://github.com/PHPCSStandards/PHPCSExtra) standard in the near future (as it is not WordPress specific).

**Comment by ghnp5** [comment]
Hello. Thank you very much.

I installed the standard with Composer, and I reference the standard in phpcs.xml using the path to the standard.

However, if I do this:

> \> phpcs --standard=WordPress -e
ERROR: the "WordPress" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz and Zend

> \> phpcs --standard="..\wp-coding-standards\wpcs\Wordpress" -e
ERROR: Referenced sniff "WordPress-Docs" does not exist

> \> phpcs --standard="..\wp-coding-standards\wpcs\Wordpress-Extra" -e
ERROR: Referenced sniff "WordPress-Core" does not exist

> \> phpcs --standard="..\wp-coding-standards\wpcs" -e
ERROR: the "..\wp-coding-standards\wpcs" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz and Zend


How do I install the Standards so that saying "Wordpress" works?

**Comment by jrfnl** [comment]
> Is PHPCSExtra maintained by the same team as this Wordpress project?

@ghnp5 PHPCSExtra is, at this time, maintained by me alone.
