### ISSUE TITLE
wc_help_tip should be marked as valid esc function

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#1890]
wc_help_tip with 2nd arg true already correctly sanitizes things.

phpcs shouldn't require an additional esc as this breaks the functionality. (I know I can work around it or just ignore it, but I think it's worth to add this to the list of esc functions)

**Comment by dingo-d** [comment]
`wc_help_tip` is WooCommerce specific, not WordPress specific function. It can be added to a custom ruleset, but not to the WPCS 🙂
