### ISSUE TITLE
Disallow mkdir in favor of wp_mkdir_p

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#1895]
## Is your feature request related to a problem?
Disallow mkdir in favor of wp_mkdir_p

To allow for extendability of the mkdir via wp_mkdir_p, to ensure the directories are automatically created with correct permissions (& also ensures that devs dont even try to "0777" work around)

**Comment by jrfnl** [comment]
Ref: https://developer.wordpress.org/reference/functions/wp_mkdir_p/

**Comment by rodrigoprimo** [comment]
@jrfnl, I was looking for good first issues to contribute to this repository and I found this one. Is the idea of this issue to add `mkdir` to the list of functions in `WordPress.PHP.RestrictedPHPFunctions`?

I noticed that `mkdir` is already flagged by `WordPress.WP.AlternativeFunctions`. Mentioning this in case it was not considered already.

Thanks

**Comment by jrfnl** [comment]
@rodrigoprimo Maybe you should ask the OP instead of me ?

It may also be that this was fixed already without anyone noticing that this issue could be closed.

**Comment by dingo-d** [comment]
You will get a warning

> File operations should use WP_Filesystem methods instead of direct PHP filesystem calls. Found: mkdir(). (WordPress.WP.AlternativeFunctions.file_system_operations_mkdir)

So we can close this.
