### ISSUE TITLE
Document Adding WPCS Via Composer to a Project in The Readme

### ISSUE THREAD

**Issue by tomjn** [WordPress/WordPress-Coding-Standards#1901]
There are various composer related methods of adding WPCS to a project, but one is missing, the one where you add some things to an existing project via the require section, or via the `composer` cli. Everything is geared towards the composer create project, or doing a global install.

The _Installing WPCS as a dependency_ looks like it would contain this information, but it does not, and seems to be focused on configuring PHPCS to pick up WPCS when installed as a dependency.

I ask because I was helping a user trying to use a global PHPCS install, and suggested using a local dependency. I thought to link them to the canonical instruction, but it appears there is none.

**Comment by tomjn** [comment]
As an example, for the HumanMade Coding standards, in their readme they say to run `composer require --dev humanmade/coding-standards` which adds the standard and PHPCS

**Comment by jrfnl** [comment]
@tomjn You're right and this is a known issue and will change with WPCS 3.0.0. I have already written the new instructions which will be far more geared towards project based Composer installs.
