### ISSUE TITLE
Update wiki for changes in 3.0.0

### ISSUE THREAD

**Issue by jrfnl** [WordPress/WordPress-Coding-Standards#1917]
As discussed in #1908, the wiki pages should be reviewed and references to "whitelisting" code should be replaced with other phrasing, such as "ignoring code"

The wiki should also be updated to reflect that support for the old-style WPCS native ignore comments has been removed in WPCS 3.0.0.

**Comment by jrfnl** [comment]
List of things which will need updating in the wiki before the 3.0.0 release:
- [ ] [Running in Travis](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Running-in-Travis) - the workflow will need to be changed to not clone the repos, but use a Composer install.
- [ ] [Customizable sniff properties](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Customizable-sniff-properties) - references to removed sniffs should be moved to the bottom with a note that those sniffs are no longer available in WPCS 3.0+.
- [ ] [Customizable sniff properties](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Customizable-sniff-properties) - the names of custom properties which have been renamed/changed/added will need to be updated.
- [ ] [whitelist code that is being flagged with errors](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors) - page probably should be removed (or rewritten)

Note: this list may not be complete....

**Comment by dingo-d** [comment]
> [Running in Travis](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Running-in-Travis) - the workflow will need to be changed to not clone the repos, but use a Composer install.

We will leave this for legacy reasons? Since we're not running checks in TravisCI any more 🤷🏼‍♂️

**Comment by jrfnl** [comment]
> We will leave this for legacy reasons? Since we're not running checks in TravisCI any more 🤷🏼‍♂️

This is not about _our_ CI, but an example for projects _using_ WPCS. There may still be (mostly commercial plugins/themes) running _their_ CI on Travis, so for them, it's good to have an example for how to set it up.

**Comment by jrfnl** [comment]
Wiki pages review list - those pages marked with a ✔️ have been updated for WordPressCS 3.0.0:

- [ ] [Home](https://github.com/WordPress/WordPress-Coding-Standards/wiki)
- [ ] [Customizable sniff properties](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Customizable-sniff-properties)
- [ ] [Fixing errors for input data](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Fixing-errors-for-input-data)
- [ ] [Sanitizing array input data](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Sanitizing-array-input-data)
- [ ] [Escaping a WP_Error object](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Escaping-a-WP_Error-object)
- [x] [Ignoring Parts of a File](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Ignoring-Parts-of-a-File)
- [x] [Running in GitHub Actions](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Running-in-GitHub-Actions)
- [x] [Running in Travis](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Running-in-Travis)
- [ ] [Setting up WPCS to work in Atom](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Setting-up-WPCS-to-work-in-Atom)
- [ ] [How to use WPCS with Eclipse and XAMPP](https://github.com/WordPress/WordPress-Coding-Standards/wiki/How-to-use-WPCS-with-Eclipse-and-XAMPP)
- [ ] [Setting up WPCS to work in Sublime Text](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Setting-up-WPCS-to-work-in-Sublime-Text)
- [ ] [Upgrade Guide to WordPressCS 2.0.0 for Developers](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Upgrade-Guide-to-WordPressCS-2.0.0-for-Developers-of-external-standards)
- [x] [Project Timeline](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Project-Timeline)

**Comment by jrfnl** [comment]
All pages have received a cursory review and been update. Further, more detailed review is welcome, but not essential for the WPCS 3.0.0 release.

Closing this issue now as fixed.
