### ISSUE TITLE
Make CapitalPDangit customizable e.g. for WooCommerce

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#1945]
## Is your feature request related to a problem?
CapitalPDangit is great for ensuring that the WordPress brand is spelled correctly.
It would be amazing if the sniff was customizable, so other brand names, e.g. WooCommerce could be checked too

## Describe the solution you'd like
Allow customizing the rule via .xml and add documentation for it to the wiki: https://github.com/WordPress/WordPress-Coding-Standards/wiki/Customizable-sniff-properties

The user provides the correctly spelled word(s), e.g. WooCommerce in the xml, e.g. as a comma separated list or as an array (whatever is preferred by the implementer)

**Comment by dingo-d** [comment]
To me this would be better suited for something like https://github.com/PHPCSStandards/PHPCSExtra/

**Comment by jrfnl** [comment]
FYI: I've just closed the issue which was opened in PHPCSExtra. A generic sniff for something like this would be a nightmare to maintain and support, so I'm not interested in having a sniff like that in PHPCSExtra.

On that note: I don't think we should want it in WPCS either.

**Comment by dingo-d** [comment]
Yeah, it sounds too generic for WPCS in my opinion, that's why I suggested extras. But I can see how difficult it would be to maintain it, so I'll close this issue 👍🏼
