### ISSUE TITLE
Add 'post_class_attr' hook

### ISSUE THREAD

**Issue by ArroWsGM** [WordPress/WordPress-Coding-Standards#1951]
## Is your feature request related to a problem?
Before v5.5.1 we used `post_class` filter to add a data attribute to the post wrapper in a hacky way. But with a 5.5 update you added an `esc_attr` in the `post_class` function. We can use an additional `esc_attr` filter, but I think it's a much more expensive solution.

## Describe the solution you'd like
Add `post_class_attr` filter to `post_class` function:
```php
function post_class( $class = '', $post_id = null ) {
	// Separates classes with a single space, collates classes for post DIV.
	echo apply_filters('post_class_attr', 'class="' . esc_attr( join( ' ', get_post_class( $class, $post_id ) ) ) . '"');
}
```

**Comment by dingo-d** [comment]
Hi @ArroWsGM.

I think you need the [core track](https://core.trac.wordpress.org/) for these kinds of suggestions. This repository is dealing with WordPress Coding Standards 🙂
