### ISSUE TITLE
Prefer __DIR__ to dirname( __FILE__ )

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#1954]
A lot of WP code that was created a long time ago, relies on `dirname( __FILE__ )` or `dirname( plugin_basename( __FILE__ ) )` (e.g. very common for loading the plugin textdomain), due to the PHP version restrictions WP had.

Since WP now has bumped the PHP min version, maybe it would be possible to prefer the use of `__DIR__`

**Comment by jrfnl** [comment]
In Core these instances were fixed via https://core.trac.wordpress.org/ticket/48082, so this may be good to safeguard.
