### ISSUE TITLE
Error message when running PHPCBF

### ISSUE THREAD

**Issue by jackjpdiscos** [WordPress/WordPress-Coding-Standards#1957]
Hi,

I get the following error when running the following command:

**phpcbf --standard=WordPress _foldername**_

> vendor/bin/phpcbf : PHP Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Trying to access array offset on value
> of type null in C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniff.php on line 1291 in
> C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Runner.php:606
> At line:1 char:1
> 
> vendor/bin/phpcbf --standard=WordPress MDJM\includes\actions.php
>   + CategoryInfo          : NotSpecified: (PHP Fatal error...\Runner.php:606:String) [], RemoteException
>   + FullyQualifiedErrorId : NativeCommandError
> 
> Stack trace:
> 
> Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Trying to access array offset on value of type null in C:\xampp\php
> \vendor\wp-coding-standards\wpcs\WordPress\Sniff.php on line 1291 in C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Runner.php:606
> Stack trace:
> #0 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniff.php(1291): PHP_CodeSniffer\Runner->handleErrors(8, 'Trying to acces...
> ', 'C:\xampp\php\ve...', 1291, Array)
> #1 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniffs\CSRF\NonceVerificationSniff.php(153): WordPress\Sniff->has_nonce_chec
> k(117)
> #2 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniff.php(832): WordPress\Sniffs\CSRF\NonceVerificationSniff->process_token(
> 117)
> #3 C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Files\File.php(496): WordPress\Sniff->process(Object(PHP_CodeSniffer\Files\LocalF
> ile), 117)
> #4 C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Files\LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
> #5 C:\xampp\php\vendor\squizlabs\php_cod in C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Runner.php on line 606
> #0 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniff.php(1291): PHP_CodeSniffer\Runner->handleErrors(8, 'Trying to
> acces...', 'C:\xampp\php\ve...', 1291, Array)
> #1 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniffs\CSRF\NonceVerificationSniff.php(153):
> WordPress\Sniff->has_nonce_check(117)
> #2 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniff.php(832):
> WordPress\Sniffs\CSRF\NonceVerificationSniff->process_token(117)
> #3 C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Files\File.php(496):
> WordPress\Sniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 117)
> #4 C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Files\LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
> #5 C:\xampp\php\vendor\squizlabs\php_cod in C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Runner.php on line 606

**Comment by dingo-d** [comment]
Hi!

You'll need to provide a bit more details. Which version of PHPCS and WPCS are you using? Did you install it via composer or globally?

On what kind of code do you get such an error? A minimum code example would also help in trying to reproduce the error.

**Comment by djstini** [comment]
I have the same issue, using PHPCS/PHPCBF version 3.6.2

**Comment by jrfnl** [comment]
Please provide a code sample with which the error can be reproduced. Without that, I'm going to close this issue in two weeks time.

**Comment by djstini** [comment]
Literally any php code produces this error for me... for example:

`<?php

    print_r( $_POST );
`

Notice the print_r has leading spaces, wich should be removed.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/80112410/157815630-c61dd62e-2a51-4e11-a220-71f94edb5cb4.png">

just noticed that another "wpcs" error shows in the tooltip when i hover over the first formatting error:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/80112410/157815673-6f5791dc-f5ee-40f4-b625-8c30fbed6b2c.png">

**Comment by jrfnl** [comment]
@djstini That's a different error and unrelated to this issue.

**Comment by djstini** [comment]
yes, i know, but the original error still exists, just added the info about the additional error, because it might help troubleshooting

**Comment by jrfnl** [comment]
@djstini Thanks, but it doesn't.

**Comment by jrfnl** [comment]
Closing for lack of actionable information with which to reproduce the issue.
