### ISSUE TITLE
Deprecate WordPress.WP.AlternativeFunctions.parse_url_parse_url

### ISSUE THREAD

**Issue by rebeccahum** [WordPress/WordPress-Coding-Standards#1970]
https://github.com/WordPress/WordPress-Coding-Standards/blob/c52e511356c65c7ee97587dcb84e98b2f90e9633/WordPress/Sniffs/WP/AlternativeFunctionsSniff.php#L102-L109

## Rationale

Since PHP require a minimum of PHP 5.6 and this seems to apply for sites 5.2~5.4+, I think it's safe to remove this sniff.

> PHP 5.4.7 expanded parse_url()’s ability to handle non-absolute url’s, including schemeless and relative url’s with :// in the path. This function works around those limitations providing a standard output on PHP 5.2~5.4+.

https://developer.wordpress.org/reference/functions/wp_parse_url/

**Comment by jrfnl** [comment]
You seem to have missed the second part of the function description:
> Secondly, across various PHP versions, schemeless URLs starting containing a ":" in the query are being handled inconsistently. This function works around those differences as well.

As far as I know, that part is still valid, which is why the `wp_parse_url()` function should still be preferred over the PHP native `parse_url()` function.

This is also why the function itself in WP has not been changed to a complete "fall-through" to the PHP native function, while the rest of the cross-version compat code within the function has been removed.

Suggest: close.

**Comment by jrfnl** [comment]
P.S.: if that second part would by now also be out of date, I'd recommend for a issue to be opened in the Core Trac to deprecate the function and for WPCS to follow the lead of WP Core in this - and not the other way around.

**Comment by pbiron** [comment]
I just opened a trac ticket about possibly replacing core's use of `wp_parse_url()`: [https://core.trac.wordpress.org/ticket/53938](https://core.trac.wordpress.org/ticket/53938).

But given the above discussion (as well as the discussion on [https://core.trac.wordpress.org/ticket/48242](https://core.trac.wordpress.org/ticket/48242), which I just became aware of), I'm now not sure the trac ticket I opened is a good idea.

@jrfnl can you please comment on the 53938?

**Comment by jrfnl** [comment]
@pbiron Thanks for the ping. Left my thoughts on the ticket.
