### ISSUE TITLE
Readme: add CI example of running WPCS via GH Actions

### ISSUE THREAD

**Issue by jrfnl** [WordPress/WordPress-Coding-Standards#1976]
## Is your feature request related to a problem?
As a lot of projects are moving from Travis CI to GH Actions for Continuous Integrations checks and the readme of WPCS currently only contains an example of how to run WPCS via Travis, it might be a good idea to add a section with an example of how to run WPCS via GH Actions.

We should maybe also consider moving these type of examples to the wiki.

**Comment by jrfnl** [comment]
@Luc45 Excellent! IIRC the wiki is publicly editable, so you should be able to create a wiki page for this.

**Comment by Luc45** [comment]
Done: https://github.com/WordPress/WordPress-Coding-Standards/wiki/Running-in-GitHub-Actions

**Comment by jrfnl** [comment]
> Done: https://github.com/WordPress/WordPress-Coding-Standards/wiki/Running-in-GitHub-Actions

Hi @Luc45, just read through it and I have a few remarks/questions:
1. Bullet 4 - the folder to be created should be `.github/workflows` not `.github/workflows/phpcs` (and that's presuming it doesn't exist yet).
2. Instead of manually handling the caching for Composer, why not use the https://github.com/ramsey/composer-install/ action runner ?
3. Why would you use Docker to run PHPCS ?
4. What about including `cs2pr` in the workflow to allow the notices from PHPCS to show in the PR file view ?
    See: https://github.com/staabm/annotate-pull-request-from-checkstyle#using-php_codesniffer
5. I would not mention a `composer.lock` file as it is irrelevant for the PHPCS run and there are plenty of projects not committing it (like WPCS).

**Comment by Luc45** [comment]
> Bullet 4 - the folder to be created should be .github/workflows

Fixed.

I have tweaked the workflow to remove Docker usage. It runs a bit faster now. I have left the Docker alternative in the example repo. https://github.com/Luc45/phpcs-ci-example/tree/main/.github/workflows

> I would not mention a composer.lock file as it is irrelevant for the

Do you know if `"ramsey/composer-install@v2"` handles the scenario where `composer.lock` is not present?

**Comment by jrfnl** [comment]
> Do you know if `"ramsey/composer-install@v2"` handles the scenario where `composer.lock` is not present?

I do know and yes, it does ;-)

**Comment by jrfnl** [comment]
> I have tweaked the workflow to remove Docker usage. It runs a bit faster now. I have left the Docker alternative in the example repo. https://github.com/Luc45/phpcs-ci-example/tree/main/.github/workflows

Looks better! Thanks for fixing that.

The actual run command is still a little overly complicated and `cs2pr` is not included. Would you like to update this yourself or are you okay with me fixing that up ?

**Comment by jrfnl** [comment]
> Please, feel free to go for it 😉

Done. Let me know what you think!

**Comment by jrfnl** [comment]
Closing as fixed by @Luc45 adding the wiki page and the reference to the wiki page having been added in #2067.
