### ISSUE TITLE
FileNameSniff: do not apply to test files

### ISSUE THREAD

**Issue by jrfnl** [WordPress/WordPress-Coding-Standards#1995]
### Current situation

The WordPress Coding Standards currently enforce file names to:
1. Be all lowercase;
2. Use hyphens instead of underscores as word separators;
3. Have a `class-` prefix for files containing classes.
4. Have a `-template` suffix for files containing template tags.

The first two rules are always applied.
The third rule is selectively applied to files containing classes which are not test classes.
The fourth rule is selectively applied to the `wp-includes` folder only.

Like with any sniff/error code, this sniff (or any of the error codes) can be disabled from a custom ruleset, either completely or selectively for certain files/directories.

### What needs to change and why

At this time, the WP Core test suite supports PHPUnit 5-7, but to allow for testing on PHP 8.1, it is very likely that a wider range of (newer) PHPUnit versions will need to be supported soon.

Aside from that, the WPCS ruleset is not only used by WP Core, but also by a large number of WP related projects, such as plugins and themes, which may already be testing against more recent versions of PHPUnit.

As of PHPUnit 9.1.0, support for test file names which do not match the class name of the test class within, is deprecated. Support is expected to be removed completely in a future PHPUnit version.
Effectively, this means that PHPUnit expects PSR4 to be followed for test classes.

Note: The file name comparison with the class name in PHPUnit is done in a case-sensitive manner (as per PSR4).

**In effect, this means that the file name rules - as they are - should no longer be applied to test classes as it will make the test classes incompatible with PHPUnit >= 9.1.0.**

The `FileName` sniff will need to be adjusted to ignore test classes completely.
Additionally a new sniff should be enabled/created to *enforce* PSR4 compliant file names for all test class files.

Ref: https://github.com/sebastianbergmann/phpunit/pull/4109/

Also related: https://core.trac.wordpress.org/ticket/53010

**Comment by oberonlai** [comment]
WordPress Coding Standard is outdated and incompatible with modern PHP. Namespace is a better way to organize the file structure.

**Comment by jrfnl** [comment]
@oberonlai This is not the place for that discussion. Nobody is forcing you to use WPCS and if you do choose to use it, it is pretty straight forward to exclude any rule you don't like.

**Comment by jrfnl** [comment]
> Additionally a new sniff should be enabled/created to enforce PSR4 compliant file names for all test class files.

Even though this issue is closed, the above has not (yet) been addressed. I'm not (yet) opening a new issue for that as we should wait to see where the discussion in https://core.trac.wordpress.org/ticket/53010 is going first.
