### ISSUE TITLE
Composer Version 2 fails with proposed install

### ISSUE THREAD

**Issue by TukuToi** [WordPress/WordPress-Coding-Standards#2000]
`composer create-project wp-coding-standards/wpcs --no-dev`

This will fail with:
```
Creating a "wp-coding-standards/wpcs" project at "./wpcs"
Installing wp-coding-standards/wpcs (2.3.0)
  - Installing wp-coding-standards/wpcs (2.3.0): Extracting archive
Created project in /Users/username/wpcs
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer[v0.5.0, ..., v0.6.2] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires dealerdirect/phpcodesniffer-composer-installer ^0.5 || ^0.6 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0, v0.6.0, v0.6.1, v0.6.2].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

**Comment by GaryJones** [comment]
Hi @TukuToi - congrats on opening issue number 2000 for this project 😄 

Have you seen https://github.com/WordPress/WordPress-Coding-Standards/issues/1979 which has a response to exactly the same issue?

**Comment by dingo-d** [comment]
Closing as a duplicate issue.

**Comment by TukuToi** [comment]
Thanks and not - did not see that, also because the title is not really clearly stating that Composer 2.0 simply wont work and we need to use an outdated variant of Composer. The ticket does not even _mention_ it.
One has to read the _error log_ to see what is mean there.

However, confirmed, it is the same problem and (which I meanwhile did) we need an _outdated Composer version_ :)

However, it still won't work.
Another topic though.

**Comment by jrfnl** [comment]
@TukuToi If should work fine with Composer 2.0.0 if you follow the instructions linked to in the other topic.
