### ISSUE TITLE
phpcs -i does not show WordPress in the list

### ISSUE THREAD

**Issue by jackjpdiscos** [WordPress/WordPress-Coding-Standards#2020]
## Bug Description
I ran the following commands:

`PS C:\xampp\php> composer global require "squizlabs/php_codesniffer=*"` and
`PS C:\xampp\php> composer global require "wp-coding-standards/wpcs=*"`

Installed fine.

I then ran

`phpcs -i`

and PS came back with:

`The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz and Zend`

I'm pulling hairs out here as to why this is not working.

| Question               | Answer
| ------------------------| -------
| PHP version             | PHP 7.4.26 (cli) (built: Nov 16 2021 18:15:31) ( ZTS Visual C++ 2017 x64 )
| PHP_CodeSniffer version | PHP_CodeSniffer version 3.6.1 (stable) by Squiz (http://www.squiz.net)
| WPCS version            | 2.3.0
| WPCS install type       | Composer global

**Comment by jrfnl** [comment]
@jackjpdiscos Well, PHPCS can't know about external standard unless you tell PHPCS about them.

As you are using Composer, the most straight forward way to solve this is to let a Composer plugin handle this for you:
```
composer global require dealerdirect/phpcodesniffer-composer-installer
```

Alternatively, you can manually register external standards with PHPCS by running the below command (replace the path with the correct path for your machine):
```
phpcs --config-set installed_paths /path/to/wpcs
```

All of this is actually explained in the readme, so you may want to read that through as well ?
