### ISSUE TITLE
Yoda Sniff seems to be incomplete

### ISSUE THREAD

**Issue by mattyrob** [WordPress/WordPress-Coding-Standards#2028]
## Bug Description
The Yoda Comparison sniff appears to be incomplete, it is missing some comparisons that are not Yoda style in the main WP code, see this example:
https://github.com/WordPress/wordpress-develop/blob/48409019b596dc679f9b89991055b4cb61743e61/src/wp-includes/canonical.php#L390
The current code is:
```
		} elseif ( is_single() && strpos( $wp_rewrite->permalink_structure, '%category%' ) !== false ) {
```
Shouldn't it be:
```
		} elseif ( is_single() && false !== strpos( $wp_rewrite->permalink_structure, '%category%' ) ) {
```
## Minimal Code Snippet
N/A

## Custom ruleset

N/A

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | 7.4.27
| PHP_CodeSniffer version | 3.6.2
| WPCS version            | 2.3.0
| WPCS install type       | git clone
| IDE (if relevant)       | Name and version e.g. PhpStorm 2018.2.2

## Tested Against `develop` branch?
- [ ] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by jrfnl** [comment]
```
strpos( $wp_rewrite->permalink_structure, '%category%' ) !== false
```

No, it doesn't need to be as `strpos()` is a function call, so there is no risk of `false` being assigned to it.

**Comment by mattyrob** [comment]
Ah, okay - thanks for the clarification, it just looked inconsistent.
