### ISSUE TITLE
Disallow using $this to add_filter/action as it's non-removable

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#2029]
## Is your feature request related to a problem?

```
add_filter( 'posts_where', array( $this, 'do_something' );
```

cannot easily be removed with remove_filter anymore (same for add/remove_action), due to the class being used as $this.
There are workarounds (https://github.com/herewithme/wp-filters-extras/, https://wordpress.stackexchange.com/a/239431) but they're cumbersome.

## Describe the solution you'd like
Disallow $this class passed in add_filter/action.
(and vice versa: only allow variables, ::class instances, or callable strings `array( 'My_Class', 'do_something' )`)

**Comment by jrfnl** [comment]
`$this` is an object instance, and the object instance will normally be stored somewhere in a variable or property elsewhere.
Yes, it may be harder to track down which variable or property you need to use to "unhook", but it can be unhooked.

Requiring `'MyClass'` or `MyClass:class` would change the requirements for hooked in callbacks in WordPress, in that those would now always have be declared as `static`.

This would be a breaking change for WordPress itself and is not something to be discussed in the Coding Standards repo, but in WordPress itself.
And considering it would be a breaking change with huge consequences, I give you very little chance of getting any traction on such a discussion.

I'm going to close this issue now as invalid as this is not something which WPCS will ever forbid, unless WordPress itself takes the lead in changing the requirements for hooked in functions.
