### ISSUE TITLE
Remove deprecation Warning on sanitize_url()

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/WordPress-Coding-Standards#2031]
## Bug Description

The use of sanitize_url() is still listed as deprecated, however as of WordPress 5.9 it has been **un** deprecated

## Minimal Code Snippet

Use sanitize_url() in a line of code.
ERROR   sanitize_url() has been deprecated since WordPress version 2.8.0. Use esc_url_raw() instead.
                  (WordPress.WP.DeprecatedFunctions.sanitize_urlFound)

This can be fixed by removing it from the deprecation list.

## Tested Against `develop` branch?

I have not tested against develop, but I did check here:

https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php#L412

So it's still on the sniffs :)

**Comment by jrfnl** [comment]
@Ipstenu Thanks for reporting this. The deprecation lists haven't been updated for WP 5.9 yet.

**Comment by SergeyBiryukov** [comment]
As of WordPress 6.1, `sanitize_url()` becomes the recommended function for sanitizing a URL, see [#WP55852](https://core.trac.wordpress.org/ticket/55852) for details.

I think it should be removed from the deprecated functions sniff (as noted above) and added to the list of [sanitizing functions](https://github.com/WordPress/WordPress-Coding-Standards/blob/95a5df2e074f757cc24f87f60b8b276c817e312f/WordPress/Sniff.php#L185).

**Comment by jrfnl** [comment]
@SergeyBiryukov It definitely will be removed when we run the deprecated code scanner before releasing the next version.
