### ISSUE TITLE
Require esc_html variations of _e/__ in all cases

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#2038]
Currently _e/__ is only required, when the string is output within the current line.

However, this runs counter to the initial idea of this rule: that all output of translating functions should be escaped before output.

Many times text is just returned and then output by WP core without any further sanitization. e.g. `plugin_action_links_` actions.

While it may be overkill in quite a few cases to call esc_html_e/__ for a __/_e, this is the only guaranteed way to ensure output from strings is escaped in all cases.
Also the performance penalty is negligible.

Should this rule be changed to always enforce the use of esc_html_e/__ in favor of _e/__ ?

EDIT: I realize this would open a pandora's box of having to escape everything all the time then though.
Maybe a static analysis psalm/phpstan plugin may make more sense for these escaping rules altogether (e.g. to check if something was already escaped, and to enfore that everything that is echoed or returned (!) must be properly escaped.

**Comment by jrfnl** [comment]
`_e/_ex()`, when used in an output statement will trigger an error along the lines of `"All output should be run through an escaping function (like %s), found '%s'."` 

When not used in an output statement, however, recommending the use of `esc_html_e()` et al would be wrong.
Escaping should always take the context _for which_ you are escaping into account. The text may be written to file/send to the database/send via an API call to be used externally etc. In each of these cases, using `esc_html*()` would have been the wrong way to escape and would break things.

Which is exactly the reason why WP (and WPCS) recommends _late_ escaping, i.e at the point where the data leaves the system.

**Comment by kkmuffme** [comment]
I'm aware of that, it's more like require escaping in the first place. (no matter if it's esc_attr, esc_html,...)

Currently the rule is like a bandaid on a bucket with 100 leaks. You press shut 5 holes, but there are still 95 holes left. This mostly comes down to WP core (but with tons of plugins having the same issues). While phpcs requires esc_html/attr/wp_kses/... for immediately output code, tons of code that is returned as part of an add_filter function is never escaped before output by WP core.
I mean while it's nice that maybe my plugin does not open an angle of attack directly when using phpcs WP rules, the amount of unescaped code by code returned by filters and output by WP code far exceeds anything that my plugin outputs.

I know this is kind of putting the cart before the horse - the real fix would of course be to run (and fix) the WP phpcs ruleset on WP core.

**Comment by jrfnl** [comment]
> I know this is kind of putting the cart before the horse - the real fix would of course be to run (and fix) the WP phpcs ruleset on WP core.

@kkmuffme Correct and no matter how good the sniffs we create, if they aren't enforced... 🤷🏻‍♀️ 

I suggest we close this issue as this is not something which can be solved in WPCS, but rather would be solved by more people _using_ WPCS..

**Comment by kkmuffme** [comment]
True. I guess we start using it for WP core.
