### ISSUE TITLE
Review sniff handling of PHP 7.3 flexible heredoc newdoc

### ISSUE THREAD

**Issue by dingo-d** [WordPress/WordPress-Coding-Standards#2039]
PHP 7.3 relaxed requirements for heredoc and nowdoc syntax.

The WPCS native sniffs which test for `T_HEREDOC` and `T_NOWDOC` tokens will need to be reviewed to make sure that they handle the changes correctly. We'll need to add additional tests that will handle the marker and text within the heredoc/nowdoc enclosing collisions.

We'd also need to see where and in which situations we can use utilities provided by PHPCSUtils package.

Refs:

- PHP RFC: https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes

Related to #764

**Comment by jrfnl** [comment]
All sniffs have been reviewed and fixed to support modern PHP in as far as my imagination reached.

If any more situations would be discovered which need to be taken into account, a new issue should be opened with code samples etc.

Closing this now as fixed.
