### ISSUE TITLE
Review sniff handling of PHP 7.3 list() reference assignment

### ISSUE THREAD

**Issue by dingo-d** [WordPress/WordPress-Coding-Standards#2041]
Since PHP 7.3 it's possible to use reference assignment with `list()`.

Code like

```php
$array = array( 1, 2 );
list( $a, &$b ) = $array;
```

Won't throw `Fatal error: [] and list() assignments cannot be by reference`. That means you'd be able to do something like this:

```php
$array = array(1, 2);
list($a, &$b) = $array;

$b = 4;
```

And the resulting `$array` would be `[1, 4]`.

PHPCSUtils [lists util](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Utils-Lists.html), already has support for detecting this so we need to examine where lists are used in WPCS, add examples and modify the sniffs to use Utils for this.

From a quick look prefix all globals sniff could be affected by this change so we need to take a look at it.

Refs:

- PHP RFC: https://wiki.php.net/rfc/list_reference_assignment

Related to #764

**Comment by jrfnl** [comment]
All sniffs have been reviewed and fixed to support modern PHP in as far as my imagination reached.

If any more situations would be discovered which need to be taken into account, a new issue should be opened with code samples etc.

Closing this now as fixed.
