### ISSUE TITLE
Review sniff handling of PHP 7.4 spread operator in array expressions

### ISSUE THREAD

**Issue by dingo-d** [WordPress/WordPress-Coding-Standards#2042]
Since PHP 7.4 you can use the spread operator (aka splat operator `...`) to unpack array expressions.

```php
$parts = array( 'apple', 'pear');
$fruits = array( 'banana', 'orange', ...$parts, 'watermelon'];
// ['banana', 'orange', 'apple', 'pear', 'watermelon'];
```

This is already covered upstream in PHPCS 3.5.0 so we need to add `Generic.WhiteSpace.SpreadOperatorSpacingAfter` to cover the case for array expression unpacking, since Core ruleset uses `Squiz.Functions.FunctionDeclarationArgumentSpacing` sniff already.

Refs:

- Rules about formatting the spread operator: #1762 
- PHP RFC: https://wiki.php.net/rfc/spread_operator_for_array

Related to #764

**Comment by jrfnl** [comment]
All sniffs have been reviewed and fixed to support modern PHP in as far as my imagination reached.

If any more situations would be discovered which need to be taken into account, a new issue should be opened with code samples etc.

Closing this now as fixed.
