### ISSUE TITLE
Review sniff handling of PHP 7.4 typed properties 

### ISSUE THREAD

**Issue by dingo-d** [WordPress/WordPress-Coding-Standards#2043]
PHP 7.4 added support for typed class properties.

```php
class User {
  private $id;
  private $name;

  public function __construct(int $id, string $name) {
    $this->id = $id;
    $this->name = $name;
  }

  // getters and setters set here
}
```

Which can be shortened to:

```php
class User {
    public int $id;
    public string $name;
 
    public function __construct(int $id, string $name) {
        $this->id = $id;
        $this->name = $name;
    }
}
```

We already include `Generic.PHP.LowerCaseType` sniff, and once we up the PHPCS version to >= 3.6.0, we should have the support for checking the typed properties in the class.

Refs:

- PHP RFC: https://wiki.php.net/rfc/typed_properties_v2

Related to #764

**Comment by jrfnl** [comment]
All sniffs have been reviewed and fixed to support modern PHP in as far as my imagination reached.

If any more situations would be discovered which need to be taken into account, a new issue should be opened with code samples etc.

Closing this now as fixed.
