### ISSUE TITLE
Review sniff handling of PHP 7.4 null coalesce equal operator

### ISSUE THREAD

**Issue by dingo-d** [WordPress/WordPress-Coding-Standards#2044]
Since PHP 7.4 null coalesce equal operator was introduced (`??=`).

Now instead of using null coalesce operator when assigning to a variable like:

```php
$_GET['variable'] = $_GET['variable'] ?? 'default';
```

You can write

```php
$_GET['variable'] ??= ''default';
```

We need to see what sniffs cover usage of this operator upstream and in the utils and if we can just use them in the WPCS ruleset.

Refs:

- PHP RFC: https://wiki.php.net/rfc/null_coalesce_equal_operator

Related to #764

**Comment by jrfnl** [comment]
All sniffs have been reviewed and fixed to support modern PHP in as far as my imagination reached.

If any more situations would be discovered which need to be taken into account, a new issue should be opened with code samples etc.

Closing this now as fixed.
