### ISSUE TITLE
How to escape JS properly?

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#2059]
Followup to https://github.com/WordPress/WordPress-Coding-Standards/issues/1270 I'd like to get some feedback on how to securely escape data inside `<script>` tags.
We inherited a lot of code with inline JS, of which I collected the most common uses cases found in there.
Which of these need to be changed to ensure the code is securely escaped?

Any feedback is greatly appreciated.

```
1) const hello_<?php echo esc_attr( $foo ); ?> = 'world';

2) const hello_world = '<?php echo esc_attr( $foo ); ?>';

3) const hello_world = <?php echo wp_json_encode( $foo ); ?>;

4) const hello_world = <?php echo (int) $foo; ?>;

5+6) const data = '<input type="checkbox" aria-label="<?php esc_attr_e( 'This is a checkbox', 'my-textdomain' ); ?>" value="<?php echo esc_attr( $my_var ); ?>">';

7) const data = '<label for="checkbox"><?php esc_html_e( 'Select All', 'my-textdomain' ); ?></label>';
```

What about `wp_add_inline_script`? Do I need to escape things I use with it? Or is this done internally? (didn't really see anything about that in core)

**Comment by jrfnl** [comment]
https://github.com/WordPress/WordPress-Coding-Standards/issues/1270#issuecomment-354455348

**Comment by kkmuffme** [comment]
Thanks I saw that, but I was unable to determine it for the above use cases.

While yes 3/4) are fine (and covered by that comment), the others are not.

`wp_json_encode` will wrap strings in double quotes, so it cannot be used in most of the examples above and in those where it an be used, it creates really awkward code like:

```
aria-label=<?php echo wp_json_encode( __( 'This is a checkbox', 'my-textdomain' ) ); ?>
```

(Which I am not sure is correct?)


I just want to clarify this here, as I think there might me some WP Trac ticket happening down the line to improve the documentation in WP core and perhaps add escaping functions to make escaping inline JS simple. At least to make it a publically, easily-accessible process to generally reduce the likelihood of JS attacks in the WP ecosystem.

**Comment by dingo-d** [comment]
Just thinking out loud here: can't you just refactor this code so there is no inline scripts with PHP in it 🤷🏼‍♂️ 

I know I always try to avoid writing inline JS (especially with PHP inside as much as possible).

What I'd do is, I'd [localize](https://developer.wordpress.org/reference/functions/wp_localize_script/) all the things I can, and then you can use this as a global object in JS files.

Would save you tons of hassle with escaping things for inline JS in my opinion.

**Comment by kkmuffme** [comment]
Answered the questions myself with EDIT in my last comment.

If possible use wp_localize_script, but in the end that's not much different from just calling `esc_attr( wp_json_encode(` on everything. In most cases esc_attr is sufficiently save, as long as the PHP is wrapped in single quotes.

For int/float types it's best (if not localized) to just typecast to (int)/(float), as that's safe even without single quotes.
