### ISSUE TITLE
wp_sanitize_redirect safe for output in redirects?

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#2069]
`wp_sanitize_redirect` is safe (maybe safer than esc_url_raw?) for URLs with query strings in JS redirects, like `window.location.href =` or `window.location.assign( ... )`

Should this be added to the allowed functions? Or phpcs:ignore everytime? Or use `esc_url_raw` in those cases too?

**Comment by dingo-d** [comment]
It already is on the list of sanitizing functions:

https://github.com/WordPress/WordPress-Coding-Standards/blob/db97a6e5d20dfca706b0951a7b3ff3c0567ec78d/WordPress/Sniff.php#L224

Not 100% sure what the question/issue is?

**Comment by dingo-d** [comment]
> The question is about output, not input

In that case, the error you are getting is correct. You **escape** on the output and **sanitize** on the input. 

Since you are _outputting_ things out, you shouldn't use sanitization functions. `esc_url_raw` should be used instead.

**Comment by kkmuffme** [comment]
Please take a look at wp-includes/pluggable.php `function wp_redirect` - WP core uses `wp_sanitize_redirect` instead of `esc_url_raw` there too (for output)

**Comment by dingo-d** [comment]
> Please take a look at wp-includes/pluggable.php function `wp_redirect` - WP core uses `wp_sanitize_redirect` instead of `esc_url_raw` there too (for output)

WP Core really shouldn't be used as a standard of good coding practices tbh (no matter how wrong this may sound).

WP core is filled with 15 years of legacy code. Some of it is being cleaned, but it's a lengthy process.

**Comment by kkmuffme** [comment]
But I think they're correct in that case?

https://developer.wordpress.org/reference/functions/wp_sanitize_redirect/
>Sanitizes a URL for use in a redirect.

And that's what is happening here. Same for my initial example. I think `wp_sanitize_redirect` is the "more" correct (compared to `esc_url_raw`) in this case?

**Comment by dingo-d** [comment]
If you check the documentation of `esc_url_raw` you can notice the more information part:

> The [esc_url_raw()](https://developer.wordpress.org/reference/functions/esc_url_raw/) function is similar to [esc_url()](https://developer.wordpress.org/reference/functions/esc_url/) (and actually uses it), but unlike [esc_url()](https://developer.wordpress.org/reference/functions/esc_url/) it does not replace entities for display. The resulting URL is safe to use in database queries, redirects and HTTP requests.
> 
> This function is not safe to use for displaying the URL, use [esc_url()](https://developer.wordpress.org/reference/functions/esc_url/) instead.

So, this is the better option to use for redirects.
