### ISSUE TITLE
[Question] When will support be given to versions 8 of php?

### ISSUE THREAD

**Issue by kallookoo** [WordPress/WordPress-Coding-Standards#2070]
Hi,

Currently versions 8 of php are not officially supported (in release), but the curious thing, according to what I have read in the develop branch, is that it is supported.
Are you planning to create a new release to include full support for php 8 versions?

**Comment by jrfnl** [comment]
Yes.

**Comment by johnnietheblack** [comment]
Is there any notion of a timeline for compat with PHP 8+? Soon various platforms are going to force higher PHP versions...

**Comment by jrfnl** [comment]
@johnnietheblack We've been working steadily on this behind the scenes for the last few months. I'm not willing to commit to a timeline, but it's coming.

**Comment by Enchiridion** [comment]
@jrfnl  Appreciate your work on this!  Any updates on PHP8.0 support?  PHP7.4 will be EOL'd in 1 month.

**Comment by jrfnl** [comment]
Working hard on it and getting closer towards a release.

**Comment by sandeshjangam** [comment]
> Working hard on it and getting closer towards a release.

@jrfnl Do you need any help to get it done faster? I would love to help you with this.

**Comment by jrfnl** [comment]
@sandeshjangam Help is always welcome.

How you can help will depend largely on your pre-existing PHPCS/Tokenizer knowledge (as I don't want to slow things down at this moment by taking on coaching - after the release I'll happily coach people):
* For a list of tasks we're working through, have a look at: https://github.com/WordPress/WordPress-Coding-Standards/issues/1877
* For low-hanging fruit, have a look at: https://github.com/WordPress/WordPress-Coding-Standards/issues?q=is%3Aissue+is%3Aopen+label%3A%22Status%3A+good+first+issue%22+milestone%3A3.0.0 and https://github.com/WordPress/WordPress-Coding-Standards/issues/1722

Feel free to claim any of the low hanging fruits and if you want to take on anything more advanced, please ping me with what you're planning to work on, so we can prevent multiple people working on the same thing.

**Comment by sandeshjangam** [comment]
@jrfnl Thanks for the details. I will have a look and will go for low-hanging fruits for now.

But after the release, I am happy to learn from you...

**Comment by jrfnl** [comment]
@sandeshjangam We're doing some issue/PR triage at the moment and just came across PR #1265. This might be a nice one to get you started ? See [my comment](https://github.com/WordPress/WordPress-Coding-Standards/pull/1265#issuecomment-1311591843) for a list of things which need to be done to get that PR to a mergable state.

**Comment by JohnnyBravoTheBest** [comment]
Hi. Any news regarding the PHP 8+ support ?  

P.S: I would help - but i am not so experienced yet.

**Comment by GaryJones** [comment]
This will be handled when WPCS 3.0 comes out. See this [pinned thread](https://github.com/WordPress/WordPress-Coding-Standards/issues/1877) for the status of that.

I'm going to close (and pin) this conversation since the question is answered by the equally general question "When will WPCS 3.0 come out?", which is handled elsewhere.
