### ISSUE TITLE
PHP Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php on line 32 in

### ISSUE THREAD

**Issue by saas786** [WordPress/WordPress-Coding-Standards#2087]
## Bug Description
Because of no PHP 8.1 support yet, it causes issue with phpcs / phpcbf.

See https://github.com/squizlabs/PHP_CodeSniffer/issues/3677

These places it needs to be fixed:

- https://github.com/WordPress/WordPress-Coding-Standards/blob/2.3.0/WordPress/Sniffs/WP/I18nSniff.php#L194
- https://github.com/WordPress/WordPress-Coding-Standards/blob/2.3.0/WordPress/Sniff.php#L1144
- https://github.com/WordPress/WordPress-Coding-Standards/blob/2.3.0/WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php#L280

Until full support is added [#2070](https://github.com/WordPress/WordPress-Coding-Standards/issues/2070), maybe a small fix release fixing it would be nice?

| Question               | Answer
| ------------------------| -------
| PHP version             | 8.1.7
| PHP_CodeSniffer version | 3.7.1
| WPCS version            | 2.3.0

## Tested Against `develop` branch?
- [x] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by jrfnl** [comment]
Closing as duplicate. This has been asked and answered multiple times before.

**Comment by saas786** [comment]
> Closing as duplicate. This has been asked and answered multiple times before.

Could you please point me to relevant questions where you have provided an answer? 
I could benefit from those replies as well.
Thanks.

**Comment by dingo-d** [comment]
I think it's this one: https://github.com/WordPress/WordPress-Coding-Standards/issues/2035

You can just search the issues for the relevant information 😉

**Comment by saas786** [comment]
> I think it's this one: #2035
> 
> You can just search the issues for the relevant information 😉

Thanks, but there is nothing there which resolves my issue, I can't use `develop` and I see no solution out there which resolves it.

I did some quick search and found no helpful solutions / answers, that's why asked you.

Anyway, I understand the reasoning, so no problem.

**Comment by GaryJones** [comment]
@saas786 

> I can't use `develop`

Why not?

**Comment by saas786** [comment]
> @saas786
> 
> > I can't use `develop`
> 
> Why not?

Because it brings in in-progress / unstable code into my repo, I don't want to chase things down if something is not working as it should. 
But if above fix is implemented and its released, I know what changes I am bringing in, and don't have to worry about it, as have been using `2.3.0` long time now.

**Comment by GaryJones** [comment]
So, you can use `develop`, but you choose not to.

You could, of course, pull in a particular commit: either the head of `develop` as it is today, or find where the fix was added that you're affected by and use that commit instead - that way the list of changes is fixed.

**Comment by saas786** [comment]
> So, you can use develop, but you choose not to.

Correct!

Awesome, thanks, that's better.

**Comment by MikeiLL** [comment]
If someone has a minute, could you please post how to upgrade to the `develop` version using Composer?

```
composer require wp-coding-standards/wpcs --dev
```

Doesn't seem to be doing the trick.

**Comment by jrfnl** [comment]
```bash
composer require wp-coding-standards/wpcs:"dev-develop"
```

You may need to add `minimum-stability: dev` as well.

**Comment by MikeiLL** [comment]
`composer require wp-coding-standards/wpcs:"dev-develop" --dev` to be specific

**Comment by MikeiLL** [comment]
@jrfnl would you mind telling me what `dev-develop` is derived from?

**Comment by jrfnl** [comment]
It's how Composer references non-tag branch names, so the `develop` branch becomes `dev-develop` and if you'd want to check out a particular WIP branch to, for instance, test a bug fix, a branch named `feature/fix-bug-xyz` would become `dev-feature/fix-bug-xyz`.

Does that answer your question ?

**Comment by MikeiLL** [comment]
> Does that answer your question ?

@jrfnl Getting there. So `dev-[branch-name](/[some-feature])` is a Composer syntax/feature, where is is checking for the string `dev-`?

You rock, by the way.

**Comment by jrfnl** [comment]
> @jrfnl Getting there. So `dev-[branch-name](/[some-feature])` is a Composer syntax/feature, where is is checking for the string `dev-`?

I think this page of the Composer documentation may help: https://getcomposer.org/doc/articles/aliases.md

> You rock, by the way.

Always nice to hear ;-)
