### ISSUE TITLE
Support "default" as value for "// phpcs:set ... minimum_wp_version"

### ISSUE THREAD

**Issue by GaryJones** [WordPress/WordPress-Coding-Standards#2171]
## Is your feature request related to a problem?
Looking at the repeated `// phpcs:set WordPress.WP.AlternativeFunctions minimum_wp_version 5.8` reset comments in a [test file](https://github.com/WordPress/WordPress-Coding-Standards/blob/feature/alternativefunctions-phpcsutils-and-modern-php/WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc), then it seems like it's an ever-increasing list of places in code where future updates would need to be made when the default value changes, which could lead to some being missed.

## Describe the solution you'd like
I wondered if something like `// phpcs:set WordPress.WP.AlternativeFunctions minimum_wp_version default` could be supported (and perhaps similar for any other numerical/version/often-changing values), such that the consuming sniff(s) could look up the `default` value in a single place and use the actual value. It centralises the default value for that WPCS release.

## Additional context (optional)
Very much an internally-facing potential improvement, which may not warrant the extra complexity, even if it was possible, which I'm not sure it is, as it may just be assigning a value to a class property - maybe a magic `__set()` in the [new trait](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Helpers/MinimumWPVersionTrait.php) could be used?

```php
public function __set( $name, $value ) {
	if ( 'minimum_wp_version' === $name && 'default' === $value ) {
		$this->minimum_wp_version = '5.8'; // Update this for each WPCS release - no need to touch test files.
	}
}
```

**Comment by jrfnl** [comment]
I like the idea.

Some notes:
* I would very much want to limit any such code to apply to tests only (there is a constant we can use for that).
* What about not having a "magic" value `default`, but just unsetting the property ?
    I.e. _if_ in a test context _and_ the `minimum_wp_version` is `null` or not set.
* Having looked deeply into magic methods and hierarchical use etc in relation to the PHP 8.2 dynamic properties deprecation, I **strongly** recommend avoiding magic method like this as the plague.
* As every sniff using the trait needs to call the `get_wp_version_from_cli()` method anyway, we should be able to solve it in that method (in combination with a `private` property which safeguards the default value - unfortunately constants in traits is not available until PHP 8.2, even though a constant would be the more appropriate container for the default value)

**Comment by GaryJones** [comment]
> I would very much want to limit any such code to apply to tests only (there is a constant we can use for that).

`PHP_CODESNIFFER_IN_TESTS` is the constant to simply check if it is defined, I believe ([source](https://github.com/michalbundyra/PHP_CodeSniffer/blob/7575ad925315c89b9abfa55aa3d4910d08f99a71/src/Files/File.php#L325)).

> What about not having a "magic" value default, but just unsetting the property ?

For my own reference, this appears to mean using phpcs:set, but with a value omitted e.g.
`// phpcs:set WordPress.WP.AlternativeFunctions minimum_wp_version`

> As every sniff using the trait needs to call the get_wp_version_from_cli() method anyway, we should be able to solve it in that method (in combination with a private property which safeguards the default value - unfortunately constants in traits is not available until PHP 8.2, even though a constant would be the more appropriate container for the default value)

👍🏻 That makes sense.

**Comment by jrfnl** [comment]
> this appears to mean using phpcs:set, but with a value omitted

Correct.

**Comment by jrfnl** [comment]
@GaryJones Just checking - did you want to implement this yourself ?

**Comment by jrfnl** [comment]
PR #2187 should fix this. Note: I have not limited it to test files as no validation was previously done on user provided ruleset `minimum_wp_version` values, so I figured, we may as well make the whole more stable.
