### ISSUE TITLE
WordPress 5.9.0 Restored `sanitize_url()` as a Proper Method for Sanitizing URLs

### ISSUE THREAD

**Issue by timnolte** [WordPress/WordPress-Coding-Standards#2189]
## Bug Description

When using the `sanitize_url` it is not recognized as being a proper sanitization method, and recommends `esc_url_raw()`.

## Minimal Code Snippet

```php
$postid = ! empty( sanitize_url( $_SERVER['REQUEST_URI'] ) ) ? url_to_postid( sanitize_url( $_SERVER['REQUEST_URI'] ) ) : $context['post']->ID;
```

The issue happens when running this command:
```bash
phpcs ...
```

... over a file containing this code:
```php
$postid = ! empty( sanitize_url( $_SERVER['REQUEST_URI'] ) ) ? url_to_postid( sanitize_url( $_SERVER['REQUEST_URI'] ) ) : $context['post']->ID;
```

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | 8.0.24
| PHP_CodeSniffer version | 3.7.1
| WPCS version            | 2.3.0
| WPCS install type       | Composer project local
| IDE (if relevant)       | Neovim

## Additional Context (optional)

https://developer.wordpress.org/reference/functions/sanitize_url/#changelog

## Tested Against `develop` branch?
- [x] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by Ipstenu** [comment]
This is addressed in https://github.com/WordPress/WordPress-Coding-Standards/issues/2031

**Comment by timnolte** [comment]
This issue is not resolve. I am running the latest release 2.3.0 and I'm stilling receiving an error:
```
 265 | ERROR | sanitize_url() has been deprecated since WordPress
     |       | (WordPress.WP.DeprecatedFunctions.sanitize_urlFound)
```

**Comment by timnolte** [comment]
Looks like this is only in the `develop` release. When are we going to get an official release published so that I can be using something stable?

**Comment by jrfnl** [comment]
@timnolte When it's ready...

**Comment by timnolte** [comment]
@jrfnl is there a list of what's outstanding and/or slated to be completed for the next release?

**Comment by jrchamp** [comment]
#2031 and the associated PR #2121 only removed the deprecation warning. `sanitize_url` is not in the list of sanitizing functions in `develop`:
https://github.com/WordPress/WordPress-Coding-Standards/blob/f4d4ff58ddfe1ca79575e60c552543966a5ed7b2/WordPress/Sniff.php#L197-L200
