### ISSUE TITLE
Use WordPress-Coding-Standard with PHP_CodeSniffer correctly "today" 

### ISSUE THREAD

**Issue by vizzale** [WordPress/WordPress-Coding-Standards#2202]
Hello everybody, mine is a question more than an issue (being only a question I thought it was more correct to consider it as an "Issue" instead of a "Dependency Change" or a "Feature request"). In the transition from Atom (which recently closed its doors) to Visual Studio Code, I decided to get my hands on my personal "Developer Kit" and therefore the tools used and the related configuration files. These also include PHP_CodeSniffer and WordPress-Coding-Standard.

Clearly it is good to clarify that I use macOS. These are the operations carried out to set up these instruments:

**1. Check that PHP is installed on the machine.**
To do this just use the `php -v` code in the Terminal.

**2. Installing the PHP_CodeSniffer**
I personally install PHP_CodeSniffer via Homebrew. The code used for the installation is as follows `brew install php-code-sniffer`.

**3. Installing the WordPress-Coding-Standards**
The team that created this standard is currently working on the new version `3.0.0`. The latest version `2.3.0` does not support PHP 8.0, 8.1, etc… therefore it does not allow the correct functioning of PHP_CodeSniffer. The problem was solved in the development version, for this reason we will use it for now by downloading it in a folder of our choice (as suggested by @jrfnl, one of the contributors of the WordPress-Coding-Standards project, in this issue https://github.com/WordPress/WordPress-Coding-Standards/issues/2035).

**4. Installing PHPCSUtils and PHPCExtra dependencies**
From what I was able to understand by reading the link https://github.com/squizlabs/PHP_CodeSniffer/issues/3110, PCSUtils and PHPCSExtra are two new dependencies that will be used in WordPress-Coding-Standards version `3.0.0`, as confirmed @jrfnl, one of the contributors to the PHP_CodeSniffer project. For this reason we will download it in a folder of our choice.

**5. Adding WordPress-Coding-Standards and the PHPCSUtils and PHPCSExtra dependencies to the PHP_CodeSniffer standards**
At this point we are going to add WordPress-Coding-Standards, and dependencies, to the standards supported by PHP_CodeSniffer via the command `phpcs --config-set installed_paths ~/namefolder/WordPress-Coding-Standards-develop,~/namefolder/PHPCSUtils-1.0.1,~/namefolder/PHPCSExtra-1.0.1` (clearly we're going to replace the `~/namefolder` folder with the one we used for the download).

This method is not the only one that can be followed, but I wanted to ask you:
1) I carried out all the steps correctly and "awarely"? The "explanations" that I "gave myself" are correct? Did I miss any other important steps?
2) Will the dependencies be integrated into WordPress-Coding-Standard in the future, or not and therefore this method to install the tools will also be useful for me in the future?

Thanks in advance for your attention and for your work.

**Comment by jrfnl** [comment]
@vizzale As @dingo-d already suggested: using Composer (global/local) to install is the preferred method and as of WPCS 3.0.0 will be **the only _supported_ method of installation**.

You can still install using the above steps, just don't expect any support from the team here.

---

> Did I miss any other important steps?

Yes, you missed checking if there were any standards already installed using `phpcs --config-show` as `--config-set` will overwrite whatever is there, which can break existing installs of other standards. (which is a prefect example of why we will only support Composer based installs, which come with a Composer PHPCS plugin which will handle the installation of external standards correctly)

**Comment by vizzale** [comment]
> Yes, you missed checking if there were any standards already installed using `phpcs --config-show` as `--config-set` will overwrite whatever is there, which can break existing installs of other standards.

@jrfnl First of all thanks for the reply and sorry for the delay.
I had done a standards check but took it for granted.

> which is a prefect example of why we will only support Composer based installs, which come with a Composer PHPCS plugin which will handle the installation of external standards correctly

So do you suggest that I also install PHP_CodeSniffer with Composer? Because currently PHP_CodeSniffer on my machine is installed via Homebrew. Do you have any well explained guide for beginners (maybe for macOS) that explains all (or almost) the steps:
1) Composer installation (preferably local version).
2) Installing PHP_CodeSniffer (only if necessary).
3) ...

Thanks in advance for your availability.

**Comment by dingo-d** [comment]
The guide is quite simple. In your project you can just do:

```
composer require wp-coding-standards/wpcs --dev
composer require dealerdirect/phpcodesniffer-composer-installer --dev
```

The second package will register the custom rulesets you decide to add to your project automatically.

Then just create a custom ruleset for your project according to [the annotated ruleset](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset) described in the phpcs repo, where you can customize the sniffs as you wish.

I recommend using composer scripts (add them to your `composer.json`) for easier script runs from your terminal

```json
"scripts": {
	"standards:check": "@php ./vendor/squizlabs/php_codesniffer/bin/phpcs",
	"standards:fix": "@php ./vendor/squizlabs/php_codesniffer/bin/phpcbf"
}
```

No need to add a dependency on phpcs, as that is already the required dependency of wpcs, so the composer will know which version to pull.

So in the end, in your project, you'll have something like

```json
{
    "name": "your-project",
    "description": "My cool project!",
    "license": "MIT",
    "require-dev": {
        "wp-coding-standards/wpcs": "^2.3",
        "dealerdirect/phpcodesniffer-composer-installer": "^1.0"
    },
    "config": {
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true
        }
    },
    "scripts": {
        "standards:check": "@php ./vendor/squizlabs/php_codesniffer/bin/phpcs",
        "standards:fix": "@php ./vendor/squizlabs/php_codesniffer/bin/phpcbf"
    }
}

```

You can add all sorts of cool things to your composer, but that's not the point of your question.

With the above composer, you'll be able to run

```
composer standards:check
```

And get the output of the violations (or no if there are none 😄).

Hope this helps.

**Comment by jrfnl** [comment]
What @dingo-d said 👍🏻 

One caveat for when WPCS 3.0.0 gets released: as of WPCS 3.0.0, you will no longer need to `require-dev` the `dealerdirect/phpcodesniffer-composer-installer` package. That will be included with WPCS as of WPCS 3.0.0. (You will still need to give permission for that plugin to run though)

**Comment by vizzale** [comment]
To avoid that too much time passes this time, I thank both of you. 
At this point to use this workflow I will wait for WPCS 3.0.0 to be ready.

But I still want to start getting familiar with Composer, so I'll do some tests on a virtual machine and if it's okay with you I'll give you some feedback on the matter. At the end of these tests I will close the issue myself.

**Comment by vizzale** [comment]
I installed Composer locally and then, as @dingo-d suggested, I installed:
- **WordPress-Coding-Standard**
`composer require wp-coding-standards/wpcs --dev`
- **PHP_CodeSniffer Standards Composer Installer Plugin**
`composer require dealerdirect/phpcodesniffer-composer-installer --dev`

> as of WPCS 3.0.0, you will no longer need to `require-dev` the `dealerdirect/phpcodesniffer-composer-installer` package

@jrfnl By this you mean that when WPCS `3.0.0` is ready there will be no need to install the plugin **PHP_CodeSniffer Standards Composer Installer Plugin** because it will be automatically installed as a dependency?

However from the tests I've done while installing these tools with Composer you still find yourself having to use the `develop` version of WPCS, so you might as well wait for version `3.0.0` to switch to Composer.

**Comment by GaryJones** [comment]
> By this you mean that when WPCS 3.0.0 is ready there will be no need to install the plugin PHP_CodeSniffer Standards Composer Installer Plugin because it will be automatically installed as a dependency?

Correct. WPCS 3.0 will [use the PHPCSUtils](https://github.com/WordPress/WordPress-Coding-Standards/blob/546f59c67854589bb8f6b49a30e642e75ff419ad/composer.json#L22) package, and that has [`require` dependency on the Composer plugin](https://github.com/PHPCSStandards/PHPCSUtils/blob/4fd2e30c7465112ca2e3646037bfb9e6f0f4d4f3/composer.json#L27).
