### ISSUE TITLE
PrefixAllGlobalsSniff - Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by thomasdevisser** [WordPress/WordPress-Coding-Standards#2203]
## Bug Description
After downloading a fresh copy of WPCS I get the following error:

```An error occurred during processing; checking has been aborted. The error message was: trim(): Passing null to parameter #2087 /Users/{username}/Developer/wpcs/WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php on line 280```

## Minimal Code Snippet
The issue happens when running this command:
```bash
phpcs index.php
```

... over a file containing this code:
```php
<?php

echo 'Hello WordPress';
```

## Custom ruleset
I'm using the WordPress-Extra standard.

## Environment
| Question               | Answer
| ------------------------| -------
| PHP version             | 8.2.1
| PHP_CodeSniffer version | 3.7.1
| WPCS version            | latest
| WPCS install type       | Standalone (through composer)

**Comment by dingo-d** [comment]
I reckon this will be fixed in version 3.0.0 since you're running it on PHP 8.2, and v3 will be PHP 8.2 compatible.

**Comment by thomasdevisser** [comment]
@dingo-d Awesome, thanks for the quick update!

**Comment by dingo-d** [comment]
No problem, also there were [issues opened](https://github.com/WordPress/WordPress-Coding-Standards/issues?q=is%3Aissue+Passing+null+to+parameter+is%3Aclosed) with a similar error so you can check them out for more context/information.

**Comment by web-programmer-here** [comment]
@dingo-d is there an eta for release of version 3? thank you

**Comment by dingo-d** [comment]
@web-programmer-here We hope by the end of March, but we are **not making any promises**. There's a lot of work to do still...

**Comment by smileBeda** [comment]
This happens as well on PHP 7 now

```
php -version
PHP 7.4.33 (cli) (built: Feb 15 2023 07:01:39) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
```

Same error:
<img width="1791" alt="Screenshot 2023-03-30 at 12 48 56" src="https://user-images.githubusercontent.com/11800236/228741425-2ba24ea4-2936-4c72-a5c9-f71dd70b2359.png">

Previously I had solved that with PHP downgrade... but this time it is not PHP version. What else can trigger this?
I _did_ update a few pip libs yesterday and Python, but... that is all unrelated to WPCS, I would assume?

**Comment by jrfnl** [comment]
@smileBeda That issues doesn't exist on PHP 7. The notice was [introduced in PHP 8.1](https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.null-not-nullable-internal). Are you sure you didn't accidentally update PHP or switch the PHP version being used by PHPCS ?

**Comment by smileBeda** [comment]
> switch the PHP version being used by PHPCS

_maybe_.
How could I check that?

Thanks!

**Comment by jrfnl** [comment]
> How could I check that?

No idea as that depends on your system set-up, your OS etc... Can't advise without more info.

**Comment by smileBeda** [comment]
Sorry the delay here.
`which php` returns `/usr/local/opt/php@7.4/bin/php` 

`php --version` returns 
```
PHP 7.4.33 (cli) (built: Apr 26 2023 19:18:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
```
    
Yet that ***** `brew` has `messed` it up again. Literally every time it is brew. I remain to be enlightened what that is all good for.

`brew list php`
```
/usr/local/Cellar/php/8.2.7/.bottle/etc/ (5 files)
/usr/local/Cellar/php/8.2.7/.bottle/var/log/php-fpm.log
/usr/local/Cellar/php/8.2.7/bin/pear
/usr/local/Cellar/php/8.2.7/bin/peardev
/usr/local/Cellar/php/8.2.7/bin/pecl
/usr/local/Cellar/php/8.2.7/bin/phar
/usr/local/Cellar/php/8.2.7/bin/phar.phar
/usr/local/Cellar/php/8.2.7/bin/php
/usr/local/Cellar/php/8.2.7/bin/php-cgi
/usr/local/Cellar/php/8.2.7/bin/php-config
/usr/local/Cellar/php/8.2.7/bin/phpdbg
/usr/local/Cellar/php/8.2.7/bin/phpize
/usr/local/Cellar/php/8.2.7/homebrew.mxcl.php.plist
/usr/local/Cellar/php/8.2.7/homebrew.php.service
/usr/local/Cellar/php/8.2.7/include/php/ (313 files)
/usr/local/Cellar/php/8.2.7/lib/httpd/modules/libphp.so
/usr/local/Cellar/php/8.2.7/lib/php/ (15 files)
/usr/local/Cellar/php/8.2.7/pecl -> /usr/local/lib/php/pecl
/usr/local/Cellar/php/8.2.7/sbin/php-fpm
/usr/local/Cellar/php/8.2.7/share/man/ (8 files)
/usr/local/Cellar/php/8.2.7/share/php/ (159 files)
```

Removed brew php, WPCS did not work at all anymore.

Bottom line, one more day of headbanging because we are stuck in 2020 and the world evolved (and I learned nothing from the 5 times I did this freaking process already)

🤷 
No ones fault but mine, I get that. It still would be nice if in a time where PHP 8+ is the _only_ PHP version that is actually still maintained, the biggest CMS in the world had a Standard that actually would allow PHP 8

**Comment by jrfnl** [comment]
@smileBeda Could you elaborate on what you mean by the following ?

> or install `develop` which does _not work_

**Comment by smileBeda** [comment]
I don’t recall the specific issue now, but I recall trying it last year and right away running into the next issue which was in some ticket here suggested to be resolved by not using develop 😅

**Comment by dingo-d** [comment]
> for example, why isn’t automattic putting some resources into this process so it can be expedited? Sorry if that’s already the Case and I don’t know. Then, it’s not enough. 😀

You'll need to ask Automattic that, not Juliette, as she is not their employee.

Putting pressure on **open-source contributors** and blaming them (your wording suggests that WPCS 3.0 not being released is blocking people from using PHP 8) certainly won't make releases happen sooner.
