### ISSUE TITLE
Compatibility with PHP 8.1 - WordPress.NamingConventions.PrefixAllGlobals

### ISSUE THREAD

**Issue by gbiorczyk** [WordPress/WordPress-Coding-Standards#2240]
## Bug Description
Using PHP 8.1 I get the following error dla all tested files:

```
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: trim(): Passing null to
   |       | parameter #1 ($string) of type string is deprecated in
   |       | .../vendor/wp-coding standards/wpcs/WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
   |       | on line 280 (Internal.Exception)
```

## Minimal Code Snippet
Just use PHP 8.1. The problem occurs even with the most simple configuration in the phpcs.xml.dist file.

The problem is in the file:
`/WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php`

It's about this code snippet:
```
// Allow overruling the prefixes set in a ruleset via the command line.
$cl_prefixes = trim( PHPCSHelper::get_config_data( 'prefixes' ) );
if ( ! empty( $cl_prefixes ) ) {
	$this->prefixes = array_filter( array_map( 'trim', explode( ',', $cl_prefixes ) ) );
}
```

I think it should be replaced with this code:
```
// Allow overruling the prefixes set in a ruleset via the command line.
$cl_prefixes = PHPCSHelper::get_config_data( 'prefixes' );
$cl_prefixes = ( is_string( $cl_prefixes ) ) ? trim( $cl_prefixes ) : '';
if ( ! empty( $cl_prefixes ) ) {
	$this->prefixes = array_filter( array_map( 'trim', explode( ',', $cl_prefixes ) ) );
}
```

## Custom ruleset
```
<?xml version="1.0"?>
<ruleset name="WordPress Coding Standards">
	<config name="installed_paths" value="vendor/wp-coding-standards/wpcs" />
	<config name="testVersion" value="7.0-" />

	<file>./src</file>

	<rule ref="WordPress" />
</ruleset>
```

## Environment
| Question               | Answer
| ------------------------| -------
| PHP version             | 8.1.0
| PHP_CodeSniffer version | 3.7.2
| WPCS version            | 2.3.0
| WPCS install type       | Composer global
| IDE (if relevant)       | PhpStorm 2022.2.3

## Tested Against `develop` branch?
- [ ] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by jrfnl** [comment]
Closing as duplicate. This has been asked and answered multiple times before.
