### ISSUE TITLE
Remove `esc_url()` and `esc_url_raw()` from list of escaping functions

### ISSUE THREAD

**Issue by westonruter** [WordPress/WordPress-Coding-Standards#2241]
## Is your feature request related to a problem?

Consider the following code (similar to what is [found](https://github.com/WordPress/wordpress-develop/blob/faee35ab0d872b4b2d53b6d50664e68588b84a78/src/wp-includes/class-wp-scripts.php#L387-L394) in core's `WP_Scripts::do_item()` method:

```php
printf( "<script src='%s' id='%s-js'></script>\n", esc_url( $src ), esc_attr( $handle ) );
```

Looks good, right? (Ignoring `WordPress.WP.EnqueuedResources.NonEnqueuedScript`.) Actually, no. It turns out that plugins have been abusing `esc_url()` here to inject additional attributes. For example, WP Engine includes the following snippet in their article [How To Defer Parsing of JavaScript in WordPress](https://wpengine.com/resources/defer-parsing-javascript-wordpress/#Method_1_Deferring_Parsing_of_JavaScript_via_functionsphp):

```php
function defer_parsing_of_js ( $url ) {
    if ( FALSE === strpos( $url, '.js' ) ) return $url;
    if ( strpos( $url, 'jquery.js' ) ) return $url;
    return "$url' defer ";
}
add_filter( 'clean_url', 'defer_parsing_of_js', 11, 1 );
```

It turns out that before `esc_url()` function returns, it passes its return value through a `clean_url` filter. Plugins can take this filter and, assuming the context that the URL is going to be output in (including single- vs double-quoted attributes), and it can manipulate the value to introduce new attributes on the tag. Such hacks should not be allowed, as they are terribly brittle (and plain terrible).

This came up recently as well for the `admin_body_class` filter ([Core-58336](https://core.trac.wordpress.org/ticket/58336)) where the lack of `esc_attr()` allows for additional attributes to be added to the `body` (as well as potential security vulnerabilities). I recall this was also a hack that used to be employed to add attributes to the `body` tag, by (ab)using the `body_class` filter (as well as adding attributes to `div.post` wrappers via `post_class` filter) which was stopped three years ago in [Core-20009](https://core.trac.wordpress.org/ticket/20009). See https://github.com/WordPress/wordpress-develop/commit/d17a57a945eccf8f01b80aeedbcede018560cdf2.

## Describe the solution you'd like

Given that attribute injection hacks involving `post_class`, `body_class`, and (soon) `admin_body_class` were all put an end to in core, I think WPCS should perhaps consider doing the same for cases involving `esc_url()`. This can be achieved by removing `esc_url()` and `esc_url_raw()` from the list of escaping functions. 

Therefore, the above snippet would need to be rewritten as in order to pass the `WordPress.Security.EscapeOutput` sniff:

```php
printf( "<script src='%s' id='%s-js'></script>\n", esc_attr( esc_url_raw( $src ) ), esc_attr( $handle ) );
```

I suggest to remove these lines or set them to `false`:

https://github.com/WordPress/WordPress-Coding-Standards/blob/fca9d9ef2dcd042658ccb9df16552f5048e7bb04/WordPress/Sniff.php#L63-L64

**Comment by smileBeda** [comment]
How would we then escape an URL?
`wp_redirect( $dynamic_url );`?

`esc_url` and `_raw` are the way to do that. If these functions are removed from valid escaping functions, what would we then use?

**Comment by westonruter** [comment]
@smileBeda In this case, no escaping is involved since nothing is being printed. In your case, `esc_url_raw()` is correct to use. This function is actually misnamed; it is actually a sanitizing function and not an escaping function. 

I'm only raising the issue for `esc_url()` being used directly for printing out in an HTML attribute. It should be wrapped in `esc_attr()` in this case.

**Comment by joemcgill** [comment]
I appreciate the intent of this issue, but currently disagree. As far as I can see, all escaping functions are passed through a filter prior to returning, so there's always the possibility that a plugin or theme is returning unescaped output by filtering the return value.

* [esc_attr](https://github.com/WordPress/wordpress-develop/blob/6.2/src/wp-includes/formatting.php#L4624-L4639)
* [esc_html](https://github.com/WordPress/wordpress-develop/blob/6.2/src/wp-includes/formatting.php#L4599-L4614)

If WP core wants to avoid this, we'd need to add some validation and cleanup to the filtered value or deprecate and remove the filters entirely.

**Comment by jrfnl** [comment]
I agree with @joemcgill and from a security perspective would be very much in favour of removing filters from these type of escaping functions. Unfortunately, I doubt such a change would be accepted in WP as it would be regarded as a BC break.
