### ISSUE TITLE
Readme instructions from develop branch don't work with PHP 8

### ISSUE THREAD

**Issue by mrsdizzie** [WordPress/WordPress-Coding-Standards#2298]
In the README it says you can add WordPress-Coding-Standards to a project with:

`composer create-project wp-coding-standards/wpcs --no-dev`

But on a machine where there is only PHP 8+ that command gives this error:

```
composer create-project wp-coding-standards/wpcs --no-devz  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer[v0.5.0, ..., v0.6.2] require php ^5.3|^7 -> your php version (8.2.8) does not satisfy that requirement.
    - Root composer.json requires dealerdirect/phpcodesniffer-composer-installer ^0.5 || ^0.6 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0, v0.6.0, v0.6.1, v0.6.2].
```

This is from the README on the `develop` branch which is supposed to work with PHP 8+

**Comment by jrfnl** [comment]
Closing as duplicate. This has been asked & answered multiple times before. Please do an issue search to see if your issue has previously been reported before opening an issue.

**Comment by mrsdizzie** [comment]
Sorry, my issue is specifically "The README of the develop branch says this works with `PHP 5.4 or higher` but the instructions right below that don't work with PHP 8+".

If this has been asked/answered it is not reflected in the README on the Develop branch that any user sees when trying to use the project. Can either the README be updated to say "This doesn't work past PHP 7.4" or "Here is the command to use it with PHP 8..."?

I appreciate all the work that goes into the next release, PHP 8 support, etc and did search and read through several PHP 8 issues but didn't see any about updating the README (sorry if I missed).

**Comment by jrfnl** [comment]
The instructions in the README apply to the last release, not to the `develop` branch as it would confuse the majority of readers. These instructions will be updated just before the release of the 3.0.0 branch.

Other than that: https://github.com/WordPress/WordPress-Coding-Standards/issues?q=+composer+installation+
