### ISSUE TITLE
"empty" will ignore sanitizing errors even when insecure

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#2346]
## Bug Description
When passing an unsafe variable to a function, but wrapping the result in empty won't report an error for missing sanitizing, even though this is unsafe.

Same also for "isset"

## Minimal Code Snippet

The issue happens when running this command:
```bash
./bin/phpcs --config-set installed_paths ../wpcs
```

... over a file containing this code:
```php
ìf ( empty( foo( $_POST['hello'] ) ) {

}
```

## Error Code
None.
Expected WordPress.Security.ValidatedSanitizedInput.InputNotSanitized

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | 7.4
| PHP_CodeSniffer version | 3.7.4
| WPCS version            | 2.3.0
| WPCS install type       | https://github.com/WordPress/WordPress-Coding-Standards#standalone

## Tested Against `develop` branch?
- [x] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by jrfnl** [comment]
Just checked and this is not even reproducable with WPCS 2.3.0.... even with the parse error still in the code....
