### ISSUE TITLE
Capital P dangit sniff autofixes 'wordpress' in comment filepaths

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/WordPress-Coding-Standards#2373]
Is this behavior expected?

<img width="938" alt="CleanShot 2023-08-30 at 08 58 24@2x" src="https://github.com/WordPress/WordPress-Coding-Standards/assets/36432/e2087613-d9c4-44a3-bac1-e7b43d23ffa9">

From https://github.com/wp-cli/export-command/pull/110

**Comment by jrfnl** [comment]
Eh... yes... sorry.. the sniff tries to exclude a _lot_ of situations to prevent false positives, but something like this - a file path in a comment with `wordpress` in the middle - is not (yet) taken into account and may be difficult to exclude completely as file paths can take all sorts of forms.

Note: this behaviour hasn't changed between WPCS 2.x and 3.x, but one of the error code from the sniff has been split into two - was `WordPress.WP.CapitalPDangit.Misspelled` - now, `WordPress.WP.CapitalPDangit.MisspelledInText` and `WordPress.WP.CapitalPDangit.MisspelledInComment`. So it could be that you need to update an exclusion ?

**Comment by danielbachhuber** [comment]
> Note: this behaviour hasn't changed between WPCS 2.x and 3.x, but one of the error codes from the sniff has been split into two - was `WordPress.WP.CapitalPDangit.Misspelled` - now, `WordPress.WP.CapitalPDangit.MisspelledInText` and `WordPress.WP.CapitalPDangit.MisspelledInComment`. So it could be that you need to update an exclusion ?

@jrfnl Ah, right. That was it! https://github.com/wp-cli/export-command/pull/110/commits/d393fe635c0deae2dbb97449abcf1e05ccc93fa9

**Comment by danielbachhuber** [comment]
@jrfnl Yep, works for me.
