### ISSUE TITLE
ERROR: Referenced sniff "PHPCSUtils" does not exist

### ISSUE THREAD

**Issue by alanef** [WordPress/WordPress-Coding-Standards#2380]
## Bug Description
3.0.0 Errors with ERROR: Referenced sniff "PHPCSUtils" does not exist

## Minimal Code Snippet

{
  "config": {
    "platform": {
      "php": "7.4.33"
    },
    "allow-plugins": {
      "dealerdirect/phpcodesniffer-composer-installer": true
    }
  },
  "require-dev": {
    "wp-coding-standards/wpcs": "^3.0"
  }
}

Fixed by downgrading to 2.30 

## Error Code
ERROR: Referenced sniff "PHPCSUtils" does not exist

## Environment
PHP 8.0.29 (cli) (built: Jun  9 2023 07:38:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.29, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.29, Copyright (c), by Zend Technologies
              | Answer
| ------------------------ | -------
| PHP version              | x.y.z
| PHP_CodeSniffer version  | x.y.z
| WordPressCS version      | x.y.z
| PHPCSUtils version       | x.y.z
| PHPCSExtra version       | x.y.z
| WordPressCS install type | e.g. Composer global, Composer project local, other (please expand)
| IDE (if relevant)        | Name and version e.g. PhpStorm 2018.2.2

## Tested Against `develop` Branch?
- [ ] I have verified the issue still exists in the `develop` branch of WordPressCS.

**Comment by wizzyto12** [comment]
Same problem

**Comment by GaryJones** [comment]
What commands are you using exactly?

To test, I created a new directory, `wordpresscs-test`, and added your `composer.json` contents to it:

<img width="1511" alt="Screenshot 2023-09-07 at 19 09 07" src="https://github.com/WordPress/WordPress-Coding-Standards/assets/88371/53404329-8ca7-423e-a328-4cd4969d831d">

I then ran `composer install` (on my machine, I shortcut that to `ci`):

<img width="1511" alt="Screenshot 2023-09-07 at 19 09 20" src="https://github.com/WordPress/WordPress-Coding-Standards/assets/88371/c0d0f7f1-a72c-4d19-8d30-051a7994dac5">

This installed fine, and you can see that the PHPCSUtils path is added to the PHPCS config via the last line.

I then checked that PHPCSUtils was one of the installed standards:

<img width="1511" alt="Screenshot 2023-09-07 at 19 10 59" src="https://github.com/WordPress/WordPress-Coding-Standards/assets/88371/391140f0-b479-40c4-987f-286f14dfba43">

I then ran PHPCS, from the version installed via the Composer Install – that is, `vendor/bin/phpcs` - **and not any global version that I may also have installed with a different configuration** (which would just be `phpcs` that would read a different binary in my `$PATH`) on a test file (screenshot trimmed, but it completed fine):

<img width="1103" alt="Screenshot 2023-09-07 at 19 13 36" src="https://github.com/WordPress/WordPress-Coding-Standards/assets/88371/0a66a4fa-6ad5-4de1-8942-3c6942da07d4">

Where does your testing differ?

**Comment by jrfnl** [comment]
Closing as [resolved](https://github.com/WordPress/WordPress-Coding-Standards/issues/2379#issuecomment-1710689373) by user reading the upgrade guide.

**Comment by alanef** [comment]
Thank you for your dismissive tone - maybe the upgrade guide should be more prominent than  burried half way down the read me.

The first user that reported this ( I did search first ) was not given an answer and if they did I wouldn't have wasted my 'user' time,  and an answer was only given after I'd spent time digging and trying to resolve.

:)

**Comment by jrfnl** [comment]
> Maybe the upgrade guide should be more prominent than burried half way down the read me?

I hear what you are saying, but if one follows the install instructions as per the readme, there is no issue. If one is upgrading from an older install, the upgrade guides are mentioned prominently in the [intro of the 3.0.0 release](https://github.com/WordPress/WordPress-Coding-Standards/releases) and spell out what you need to do.

I've spend a lot of time making sure those docs are available and straight forward to follow guides. I know you've removed your remark about my "dismissive tone" from the above comment, but that doesn't mean your comment was ever justified. If all the information is made available in extensive guides and people don't bother to read, then yes, no matter how annoying for you, this is something you could have solved by reading the docs, but instead you choose to ask unpaid maintainers to help you, effectively wasting our time and then you think it is justified to make a remark about my "tone" ?

**Comment by alanef** [comment]
I apologize. Now I know what length you and the team have gone to and I simply missed it.  Mika had X-Posted the core announcement   to make plugins - but I missed that too ( it coincided with vacation ).   You are not to know that as a developer for more than 40 years  - one way to wind me up is to call me a user - its a language thing and I shouldn't have risen to it - hence my edit.

**Comment by jrfnl** [comment]
@alanef Apology accepted. Hope WordPressCS 3.0.0 will serve you well.
