### ISSUE TITLE
Internal error in WordPress/Sniffs/WP/PostsPerPageSniff.php

### ISSUE THREAD

**Issue by anomiex** [WordPress/WordPress-Coding-Standards#2390]
## Bug Description

This code fails if the `$val` is an empty string.
https://github.com/WordPress/WordPress-Coding-Standards/blob/e02529fec40ff219653182d43866e6d6d9e3b47d/WordPress/Sniffs/WP/PostsPerPageSniff.php#L81
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been aborted. The error message was: Uninitialized string offset 0 in /tmp/test/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/WP/PostsPerPageSniff.php on line
   |       | 81 (Internal.Exception)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

## Minimal Code Snippet

The issue happens when running this command:
```bash
vendor/bin/phpcs -s --standard=WordPress --sniffs=WordPress.WP.PostsPerPage test.php
```

... over a file containing this code:
```php
<?php

$query = 'posts_per_page=' . (int) $_POST['limit'];
```

## Error Code

WordPress.WP.PostsPerPage

## Environment

| Question                 | Answer
| ------------------------ | -------
| PHP version              | 8.2.10
| PHP_CodeSniffer version  | 3.7.2
| WordPressCS version      | dev-develop e02529f, also tried with 3.0.1
| PHPCSUtils version       | 1.0.8
| PHPCSExtra version       | 1.1.1
| WordPressCS install type | Composer project local
| IDE (if relevant)        | None

## Tested Against `develop` Branch?
- [x] I have verified the issue still exists in the `develop` branch of WordPressCS.

**Comment by jrfnl** [comment]
Thanks for reporting this @anomiex !
