### ISSUE TITLE
Whitespace added before binary or operators

### ISSUE THREAD

**Issue by kkmuffme** [WordPress/WordPress-Coding-Standards#2403]
WPCS 3.0.1

https://github.com/squizlabs/PHP_CodeSniffer/issues/3922

**Comment by jrfnl** [comment]
https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#space-usage

**Comment by jrfnl** [comment]
P.S.: nothing to do with WPCS 3.0.1. This sniff has been in WPCS in [one form or another](https://github.com/WordPress/WordPress-Coding-Standards/commit/15936225dce87b9a6d7b23e6e0d166ca42920d81) since the dawn of time (`0.3.0`).
