### ISSUE TITLE
Exclude patterns in .phpcs.xml.dist not honored

### ISSUE THREAD

**Issue by mackensen** [WordPress/WordPress-Coding-Standards#2433]
## Bug Description
I'm upgrading an older plugin project to use the current versions of this library:

```json
    "require-dev": {
        "wp-coding-standards/wpcs": "^3.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.0"
    },
```

I'm running `vendor/bin/phpcs -ps . --standard=WordPress` from the root of my plugin folder. The command runs out of memory because it traverses `node_modules`. I'm using the sample `phpcs.xml.dist.sample` with the standard exclusions that should prevent this behavior:

```xml
	<!-- Exclude the Composer Vendor directory. -->
	<exclude-pattern>/vendor/*</exclude-pattern>

	<!-- Exclude the Node Modules directory. -->
	<exclude-pattern>/node_modules/*</exclude-pattern>
```

If I run the command specifying the exclusions it runs as expected without the memory error: `vendor/bin/phpcs -ps . --standard=WordPress --ignore=vendor,node_modules`.

## Environment

| Question                 | Answer
| ------------------------ | -------
| PHP version              | 7.4.33
| PHP_CodeSniffer version  | 3.9.0
| WordPressCS version      | 3.0.1
| PHPCSUtils version       | 1.0.10
| PHPCSExtra version       | 1.2.1
| WordPressCS install type | Composer project local
| IDE (if relevant)        | N/A

## Tested Against `develop` Branch?
- [x] I have verified the issue still exists in the `develop` branch of WordPressCS.

**Comment by jrfnl** [comment]
1. This is not something which WPCS can do anything about, WPCS doesn't do the filtering. You'd be better off reporting this to the [PHP_CodeSniffer project](https://github.com/PHPCSStandards/PHP_CodeSniffer).
2. Not sure what versions you are upgrading _from_, as those were not mentioned, but the filter behaviour in PHPCS itself hasn't undergone any changes in the last few years, so I don't understand how this is related to your upgrade to WPCS 3.0.

**Comment by mackensen** [comment]
I'm upgrading from 2.1, and I'll follow up with that project. Thanks!

**Comment by mackensen** [comment]
I think the specific issue is that I didn't realize/remember that specifying the standard (`--standard=WordPress`) means any custom ruleset you define is ignored.

**Comment by jrfnl** [comment]
> I think the specific issue is that I didn't realize/remember that specifying the standard (`--standard=WordPress`) means any custom ruleset you define is ignored.

@mackensen Ah, I missed that you were running with `--standard=WordPress` in the original command... In which case, yes, 100% correct.

And for anyone else trying to understand this:
* When no `--standard=...` is passed on the command-line, PHPCS will look for a `[.]phpcs.xml[.dist]` file and use that as the ruleset/standard. When that such a file is not found, it will fall-back to the default standard.
* When passing `--standard=...` on the command-line, PHPCS will not even look any further, it will use whatever standard is provided. I.e. command-line args will always overrule everything.
    Keep in mind, you can pass multiple standards as a comma-separated list and they don't all have to be named ones either: `--standard=WordPress,myphpcs.xml`.
    It will be rare to need this though and you'd be better off documenting the rules which apply to your project in a project specific `[.]phpcs.xml[.dist]` file.
