### ISSUE TITLE
ERROR: Referenced sniff "Universal.NamingConventions.NoReservedKeywordParameterNames" does not exist

### ISSUE THREAD

**Issue by picard102** [WordPress/WordPress-Coding-Standards#2435]
Hitting this error whenever I run phpcs. 

PHPCS is installed via Brew. 

```
% phpcs --standard=WordPress --report=verbose /Users/johnleschinski/Sites/awards/src/404.php
ERROR: Referenced sniff "Universal.NamingConventions.NoReservedKeywordParameterNames" does not exist

Run "phpcs --help" for usage information
```

```
 $phpCodeSnifferConfig = array (
  'installed_paths' => '/Users/username/.composer/vendor/wp-coding-standards/wpcs,/Users/username/.composer/vendor/phpcsstandards/phpcsutils',
  'default_standard' => 'WordPress',
);

```

**Comment by jrfnl** [comment]
Please read the [upgrade guide for WordPressCS 3.0.0](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Upgrade-Guide-to-WordPressCS-3.0.0-for-ruleset-maintainers).

> While installing WordPressCS without Composer is still possible, no support will be given anymore for such installs.

**Comment by picard102** [comment]
For anyone who's looking for a fix while not changing their whole setup. 
I had to add the phpcsextra path to the installed_paths. 
You can find the file to edit by using phpcs --config-show, which in my case was /opt/homebrew/Cellar/php-code-sniffer/3.9.0/bin/CodeSniffer.conf

You can also do it via phpcs --config-set installed_paths YOURPATH/wp-coding-standards/wpcs/Wordpress,YOURPATH/composer/vendor/phpcsstandards/phpcsutils,YOURPATH/composer/vendor/phpcsstandards/phpcsextra
