### ISSUE TITLE
should PEAR.Functions.FunctionCallSignature.Indent be applied on javascript files ?

### ISSUE THREAD

**Issue by naveen17797** [WordPress/WordPress-Coding-Standards#2441]
## Bug Description

should `PEAR.Functions.FunctionCallSignature.Indent` be applied on javascript files ?

This is related to issue https://github.com/WordPress/WordPress-Coding-Standards/issues/2395, i tried to fix the file with @wordpress/scripts format command, yet it didn't fix this file. So is it right to ignore javascript files from this sniff ?

**Comment by jrfnl** [comment]
@naveen17797 Javascript support is being removed from PHPCS and by extension from WPCS. Use Javascript specific tooling like eslint/jslint and such instead.

**Comment by naveen17797** [comment]
So if i understood correctly, its safe to disable wpcs for all other extensions except php ? I am using wpcs version 3.0.1

**Comment by jrfnl** [comment]
@naveen17797 Providing you use tooling like eslint/jslint etc, then, yes, I'd recommend disabling JS scanning via WPCS.

**Comment by naveen17797** [comment]
Thanks for the clarification :-)
