### ISSUE TITLE
Rules for space indentation instead of tabs, specifically in multiline arrays

### ISSUE THREAD

**Issue by pdewouters** [WordPress/WordPress-Coding-Standards#2448]
## Is your feature request related to a problem?
Enforcing spaces for indentation

## Describe the solution you'd like
I want to introduce WP standards in a codebase that is using spaces for indentation, so instead of converting all indentation to tabs, I'd like to enforce 2 spaces as per existing style.
this config gets me nearly there https://gist.github.com/pdewouters/39d6b4f1c2d60e5c1538163774c8ed18

But I still get some errors related to array indentation, it thinks it should be 4 spaces instead of 2.

## Additional context (optional)

See screenshot: the first line has no errors because it has 4 spaces indent but the next ones throw an error. It should be the reverse

![Screenshot 2024-05-30 at 13 27 49](https://github.com/WordPress/WordPress-Coding-Standards/assets/30460/e0c59449-55d0-439c-ab02-cbb02b838e65)

- [ ] I intend to create a pull request to implement this feature.

**Comment by jrfnl** [comment]
@pdewouters As is clearly mentioned in the templates: please do not post screenshots, post a code sample the report can be tested with.

As things are, this is not actionable.

**Comment by dingo-d** [comment]
This looks like a discussion topic, not an issue with WPCS. Can you open this as a discussion instead @pdewouters ?

**Comment by pdewouters** [comment]
@dingo-d where are the discussions?

**Comment by dingo-d** [comment]
You don't see the https://github.com/WordPress/WordPress-Coding-Standards/discussions link? 🤔

**Comment by pdewouters** [comment]
I do now, thanks
