### ISSUE TITLE
Add its own class for curl on WordPress.WP.AlternativeFunctions

### ISSUE THREAD

**Issue by stefanolissa** [WordPress/WordPress-Coding-Standards#2451]
Hi, since curl sometimes needs to be used, for example, when the `multi_exec()` is used and cannot be replaced by `wp_remote_*`, having a specific class like WordPress.WP.AlternativeFunctions.Curl to group all the curl functions would help to disable that sniff in a file. Otherwise a lot of `phpcs:disable` comments should be added.

I tried to seek a way to disable the sniffs with a "start-with" rule, but I didn't find it.

Thanks.

**Comment by jrfnl** [comment]
Not exactly what you are looking for, but disabling the `curl` group (or any group) is a existing feature and has been around for forever. See: https://github.com/WordPress/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#various-sniffs-excluding-a-group-of-checks

This property works code-base wide though, so is not file specific.

**Comment by stefanolissa** [comment]
That's perfect, thank you!
