### ISSUE TITLE
Benefiting from WPCS without formatting

### ISSUE THREAD

**Issue by szepeviktor** [WordPress/WordPress-Coding-Standards#2497]
## Describe the solution you'd like

I'd like to use all features of WPCS except indentation/formatting and naming/casing.

Is there a straight-forward way to do it?
Currently I disable those rules one-by-one.

Thank you.

**Comment by jrfnl** [comment]
Previously discussed in #740, #1067 and #1157 and rejected. Doing what you're doing is currently the suggested solution.

**Comment by szepeviktor** [comment]
Thank you Juliette.
