### ISSUE TITLE
Auto escaped methods

### ISSUE THREAD

**Issue by Zackio** [WordPress/WordPress-Coding-Standards#413]
Hi,

Is it possible to add a function in a static class to the auto escaped functions list? I can escape any function from the class but not the function specifically. ie: classname::function_name

**Comment by JDGrimes** [comment]
No, that isn't supported. The feature could be added though.

**Comment by JDGrimes** [comment]
Related: #473

**Comment by adrianstaffen** [comment]
Are there any news on this?
Additionally, I need to add non-static class functions (e.g. $class->function_name) and functions inside a namespace (e.g. NamespaceName\function_name)

**Comment by jrfnl** [comment]
Even though this was the earlier issue, another issue was opened since and has a lot more discussion on it, including implementation ideas, so I'm going to close this issue in favour of the more recent issue #1176.
