### ISSUE TITLE
Preferred upgrade path when installed using create-project?

### ISSUE THREAD

**Issue by jjeaton** [WordPress/WordPress-Coding-Standards#481]
I can't seem to find any information on how to upgrade to the latest release of wpcs when installed using this:

`composer create-project wp-coding-standards/wpcs:dev-master --no-dev`

Running `composer update` only updates the dependencies. Is there a recommended way to keep this up to date with composer, or do I need to delete the directory and run `composer create-project wp-coding-standards/wpcs:dev-master --no-dev` again?

**Comment by samwilson** [comment]
Not a direct answer to your problem, but I always install this with `composer global require wp-coding-standards/wpcs:dev-master` because it makes updating so simple (just a matter of running `composer global update`, which I do regularly anyway).

**Comment by jjeaton** [comment]
@samwilson yeah, I originally had it that way but changed the to install instructions in the README. I'm thinking the README should maybe suggest installing globally with composer over create-project as not being able to update it is an issue.

**Comment by samwilson** [comment]
@jjeaton Yeah I reckon `global require` is easier. :)

**Comment by jjeaton** [comment]
Any chance of updating the README or providing recommended install instructions that include the ability to upgrade to the latest version?

**Comment by JDGrimes** [comment]
It looks like @Rarst is the one that originally suggested using `composer create-project` via https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/commit/a887ff6fda6fbc360bdc9136ff17a08c20ee577e. I think he is a Composer guru, so maybe he could enlighten us as to why he originally suggested that and if there is a way to update from there.

**Comment by Rarst** [comment]
If you chose to keep `.git` directory during install then update to latest master would be `git pull && composer install`. Otherwise you would have to delete the dir and make a fresh one.

Personally I have a local project for tools (never got on global install bandwagon).

Does `composer global update` actually update `dev-master` versions? It tends not to for normal non–global installs.

**Comment by danielbachhuber** [comment]
+1 to `composer global require`:

```
export PATH="$HOME/.composer/vendor/bin:$PATH"
composer global require wp-coding-standards/wpcs
phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
```

I ended up on this issue because I was curious why `composer create-project` was the recommended behavior.

**Comment by grappler** [comment]
PHPCS also recommends `composer global require "squizlabs/php_codesniffer=*"` https://github.com/squizlabs/PHP_CodeSniffer

I think that is better than `composer create-project`. Or the WPCS would be added to a project locally.

**Comment by Rarst** [comment]
I think our defaults are reasonable and we create no _roadblocks_ for other configurations for those who want it, I would say good enough for now. :)

If one knows difference between creating project and global install then they can pick which suits their needs more just fine.

**Comment by jjeaton** [comment]
To me, updating the README to outline the options (plus how to upgrade) would be useful.

Even if it's to say, "if you use our recommended install method, you have to delete it and re-install with `create-project` to update". I agree that `composer global require` seems like a better option, at least for keeping up to date with `wpcs` (if you aren't contributing directly to its development).
