### ISSUE TITLE
Variable "Name" is not in valid snake_case format

### ISSUE THREAD

**Issue by octalmage** [WordPress/WordPress-Coding-Standards#657]
The WP_Theme class has variables that are not snake_case, so accessing any of them throws this error: 

```
 361 | ERROR | [ ] Variable "Name" is not in valid snake_case format
```

The error is thrown for this code: 

https://github.com/wpengine/phpcompat/blob/master/src/wpephpcompat.php#L361

**Comment by octalmage** [comment]
I found https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/574 which will probably work for me, but this could possibly be included.

**Comment by jrfnl** [comment]
Related to #1102 and #1623 which discuss adding the ability to scope whitelisted variables.

**Comment by jrfnl** [comment]
Clsoing in favour of #1102 and #1623
