### ISSUE TITLE
Include README section about support terms

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/WordPress-Coding-Standards#705]
For users who have questions about how to integrate WPCS, it would be helpful to have a section about support in the README.

**Comment by dingo-d** [comment]
The question is a bit vague on what 'integrate WPCS' means. 

We do have [Wiki pages](https://github.com/WordPress/WordPress-Coding-Standards/wiki) with an explanation of how to use the standards in the IDEs and in the CI pipeline.

And phpcs itself has a [wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset) on how to use the ruleset.

Hope this covers the integration part.
