### ISSUE TITLE
Utilizing the unserialize() function on untrusted data structures

### ISSUE THREAD

**Issue by grappler** [WordPress/WordPress-Coding-Standards#727]
The VIP currently has a warning sniff for `unserialize()`. It would be good to make a stricter check to catch this issue. The check will be moved to DiscouragedFunctions in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/633

https://pagely.com/blog/2016/12/tracking-wp-php-object-injection-attackers-in-november/
https://www.owasp.org/index.php/PHP_Object_Injection

**Comment by jrfnl** [comment]
Not sure what you have in mind for this ? The warning could of course be changed to an error, but that can just as easily be ignored.

Unless someone can clarify what such a stricter check should sniff for, I suggest closing this issue.

**Comment by grappler** [comment]
I am not sure anymore.

**Comment by jrfnl** [comment]
@grappler Thanks for letting us know and closing the issue. How's life ?
