### ISSUE TITLE
Unable to use customVariablesWhitelist to whitelist $I variable

### ISSUE THREAD

**Issue by westonruter** [WordPress/WordPress-Coding-Standards#859]
Codeception uses `$I` by convention for the AcceptanceTester. I've found that I'm unable to include it in `customPropertiesWhitelist` to whitelist it, while `customVariablesWhitelist` is deprecated in favor of the former. Key code in question is in `WordPress_Sniffs_NamingConventions_ValidVariableNameSniff`, particularly in the `elseif` where it is not checking if the non-property `$var_name` is whitelisted:

```php
if ( self::isSnakeCase( $var_name ) === false ) {
	if ( $in_class && ! isset( $this->whitelisted_mixed_case_member_var_names[ $var_name ] ) ) {
		$error      = 'Object property "%s" is not in valid snake_case format';
		$error_name = 'NotSnakeCaseMemberVar';
	} elseif ( ! $in_class ) {
		$error      = 'Variable "%s" is not in valid snake_case format';
		$error_name = 'NotSnakeCase';
	}

	if ( isset( $error, $error_name ) ) {
		$data  = array( $original_var_name );
		$phpcs_file->addError( $error, $stack_ptr, $error_name, $data );
	}
}
```

**Comment by jrfnl** [comment]
Sounds like a question to ask yourself: why did you originally revert checking for this ? Related commit: 4753fb14d446348fd7444707885eac3264ca8c5f

(I later introduced the class/non-class distinction)

**Comment by westonruter** [comment]
That's a great question! 😦 😕

**Comment by JDGrimes** [comment]
Yeah, I have to just exclude this sniff from running over the acceptance tests. In theory though, I guess the variable name `$I` is only convention and `$i` or something else could be used instead, though I haven't tried it.

I'd be OK with reintroducing the custom variables whitelist separate from the properties whitelist. Although anybody who is still using it despite the deprecation would then have their list of properties being used as a list of variables again.

**Comment by GaryJones** [comment]
> In theory though, I guess the variable name $I is only convention and $i or something else could be used instead, though I haven't tried it.

Actually, I think it is case-sensitive.

**Comment by jrfnl** [comment]
Variables names are case-sensitive, but the convention is just a convention and could be interpreted as case-insensitive ?

**Comment by GaryJones** [comment]
I think it was @tnash who said he'd wasted time trying to use `$i`.

**Comment by jrfnl** [comment]
Is this still an issue ? If so, please leave a comment.

If there is no comment within the next 30 days or so, I suggest closing this issue.
