### ISSUE TITLE
Warn on test class files prefixed with `test-`

### ISSUE THREAD

**Issue by GaryJones** [WordPress/WordPress-Coding-Standards#892]
Following on from #882, I propose a `WordPress-Extra` check that would look at files with test classes for the presence of a filename prefix of `test-`, and throw a warning if found.

WP Core doesn't use prefixes, and PHPUnit doesn't appear to have ever support a `<directory prefix="...">` attribute either (so was never using the value anyway).

There should be an option to turn this check off, for those that really don't want to comply.

**Comment by jrfnl** [comment]
> There should be an option to turn this check off, for those that really don't want to comply.

Like `<exclude name="sniffname" />`?

**Comment by GaryJones** [comment]
Yes. I realise my request for an option was redundant, but wanted to emphasis that there was a way for people to opt out of this check, and that the could continue using the `test-` if they wish :-)

**Comment by jrfnl** [comment]
If I'm honest, I don't see this as a sniff for WPCS. The [handbook doesn't have any rules about naming test files](https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#naming-and-organization), so until it does, I don't think WPCS should enforce anything related to this.

Suggest: close

**Comment by GaryJones** [comment]
> The [handbook doesn't have any rules about naming test files](https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#naming-and-organization), so until it does, I don't think WPCS should enforce anything related to this.

It kinda does be example, a [bit further down](https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#test-classes):

> Test class names should reflect the filepath, with underscores replacing directory separators and TitleCase replacing camelCase. Thus, the class Tests_Comment_GetCommentClass(), which contains tests for the get_comment_class() function, is located in tests/comment/getCommentClass.php.

An unscientific skimming of https://core.trac.wordpress.org/browser/trunk/tests/phpunit/tests suggests no test class files start with `test-`, so while this is probably one of those to get added to the handbook first, the follow-up sniff idea could probably still stand.

**Comment by jrfnl** [comment]
I don't think we should add a _negative_ rule - "don't prefix with `test-`", I think we'd rather want it to be a _positive_ rule like "Test file names should match the name of the class therein".

I also seem to remember PHPUnit actually enforcing this as of 9.?, but can't find the reference to it at this moment.
Similarly, I think there is at least one Trac ticket open in which this is being discussed, but I can't seem to find it...

**Comment by GaryJones** [comment]
https://core.trac.wordpress.org/ticket/53010#comment:5 and #1995.

**Comment by jrfnl** [comment]
Ha! Your search-fu is clearly better than mine. Thanks for those links. 

Would it make sense to close this ticket in favour of #1995 ?

**Comment by GaryJones** [comment]
Agreed.
