### ISSUE TITLE
JS prefixing check

### ISSUE THREAD

**Issue by dingo-d** [WordPress/WordPress-Coding-Standards#930]
Building on #907, a similar check should be made for JavaScript functions.

Atm the only thing that I can think of is creating a custom lint, that should be then added along with the [WPTRT 120 issue](https://github.com/WPTRT/WordPress-Coding-Standards/issues/120), for general line check.

**Comment by jrfnl** [comment]
@dingo-d FYI: PHPCS already contains a tokenizer for JS as well. It's not as fully featured as the PHP one, but I got a suspicion that it shouldn't be hard to create a "normal" PHPCS sniff for this (or add to the `PrefixAllGlobals` one).

**Comment by jrfnl** [comment]
With an eye on PHPCS dropping support for JS in PHPCS 4.0 and most of the JS checking having moved to ESLint now anyway, I suggest closing this as `wontfix`.
